### ISSUE TITLE
Dynamic input and output

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#10]
If the output of step is dynamically determined, for example, by running `glob.glob` from output directory, the output
might be empty or wrong at the planning stage. For example

```python
[100]
output: '*.bam'

[200]

run('samtools sort')
```

Step 200 might get an empty list at the planning stage and will be treated as a leaf/starting step with no input, and
causes an error.

Solution:

* A `dynamic` section option to tell SoS that the output of step 100 is dynamic?
* Holding off executing step 200 if it does not have explicit input instead of relying
  on output of previous step?
* A `dynamic` property to related variables.
* `dynamic` input, output, and depends option.

A dynamic option to `input` and `output` directives seems to be best, but `dynamic('*.txt')` is also acceptable. The problem with the latter is that `dynamic(func(args))` looks a bit strange because essentially speaking `dynamic` delay evaluation of string (`*.txt`) so the format `dynamic(func(args))` can be a bit confusing.

**Comment by BoPeng** [comment]
Dynamic input and output has been implemented through `dynamic=True` option. This changes the execution logic quite a bit and caused a lot of trouble. In particular, we are required to retrieve output files from signatures created from dynamic input or output files.

**Comment by gaow** [comment]
This is a huge step forward! Looking to try it out. I take it that next is auxiliary step, then DAG, then cluster support, and we should be ready for peer review :)

**Comment by BoPeng** [comment]
I am not quite happy with the code because it is becoming too complicated and need to be separated into smaller classed and functions. I guess we can clean up the code later.

**Comment by gaow** [comment]
Hmm ... I guess we can refactor the code if it does not hinder the implementation of DAG (by me because I assume I need to understand this new structure to do it) or future maintenance of features added hereafter.

**Comment by BoPeng** [comment]
The order is wrong. The next step should be DAG because auxiliary steps have to be inserted to the DAG, not to the sequential steps. Suppose `SoS_Step.run()` is complete and correct, I think you can rewrite `SoS_Workflow.run()` into `SoS_Workflow.dryrun()` (copy the code), `SoS_Workflow.prepare()` (prepare and get the DAG), and `SoS_Workflow.run()` to execute with DAG. Auxiliary steps can be added to the DAG building step rather easily because the auxiliary steps are already in the workflow but are not used.
