### ISSUE TITLE
Remove temporary scripts

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#101]
I've been running a lot SoS today, and when I tried to list  `/tmp` I see `Display all 29968 possibilities?`. It is almost 30K files today. It will erase tomorrow as I reboot, but for a cluster I guess these files will remain  there.

Should we clean it up somewhat? Perhaps it is most straightfoward to write to `/tmp/.sos`, instead to `/tmp`, and remove `.sos` every rerun?

**Comment by BoPeng** [comment]
SoS does not write to `/tmp`, are you sure those are generated by SoS?

**Comment by BoPeng** [comment]
My mistake. I thought that these files are removed, but they are not. It should be fixed now.
