### ISSUE TITLE
runtime option inline=True or submit=False

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#111]
There are cases that users would like to use the script format to specify actions that are long, but execute rather quickly. In this case it is preferred that the step process is not submitted as an external task, and rather be executed by SoS. We can use an option to enforce this. For example

```
python:  inline=True
   python_script
```

or
```
python:  submit=False
   python_script
```

The use of keyword `submit` has the advantage that other than `submit=True`, `submit=False`, we can use `submit=some_command` to submit the job.

**Comment by gaow** [comment]
> `submit=some_command`

What commands can we possibly submit to, given the action name pretty much determined the command? I remember we have discussed about possibility to allow for additional command line switch though, e.g. `python -w xxx`. Also it looks like it's a Python only option?

**Comment by BoPeng** [comment]
No, here submitter is something like 

```
ssh cluster qsub -q long {script}
```

So without a submitter, the script is inline, with `submitter=True`, script is a standalone script that will be handled by SoS, and with a specific submitter the script can be handled quite differently.

**Comment by BoPeng** [comment]
Another option is making

```
action: action_options
   script
```

strictly an alias for

```
action(script, action_options)
```

so that the script is by default executed by SoS. Then at least the following is clear on which options are run time options, and which options are action options.

```
task: run_time options
action: action options
   script
```

The downside is that

```
run: concurrent=True
   script
```
need to be written as

```
task: concurrent=True
run:
   script
```

**Comment by BoPeng** [comment]
No longer needed by the current task design.
