### ISSUE TITLE
A 'lock' in current SoS folder

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#113]
I'm not sure if there will be a problem to run multiple SoS instances in the same folder at the same time. I imaging this can be problematic when these scripts overlap in some signatures. If so, we'll likely run into problems particularly when SoS scripts are submitted to cluster directly via qsub. I have not done this myself so I just want to check if this is valid concern, and if so, whether or not adding a lock file would help.

**Comment by BoPeng** [comment]
This is indeed a problem and we have a reserved `blocking` keyword for this. We will look into this in detail later.

**Comment by BoPeng** [comment]
For runtime signatures, we can create a signature for each run (from command line and script) and use the ID in various files. For example, we can have

```
.sos/.runtime_48de3b
```

This cannot solve conflicts between output files though.

**Comment by gaow** [comment]
This issue stung me hard today! I had a long running job (over 12 hours) and at the 10th hour I executed another SoS command in the same directory by accident. My job signatures were all messed up ...

**Comment by BoPeng** [comment]
Can -F save some results?

**Comment by gaow** [comment]
I did not realize the signature issue until I started another run yesterday; I left the office to let it run over night. It's complete now but indeed next time I'll restart with `-F`!

**Comment by gaow** [comment]
A lot times I have the urge to run multiple SoS commands under the same folder. Currently conflicts occurs as described above. I wonder if it is possible to instead of having to use `.sos` folder to store everything, would it be possible to specify another folder to cache the data? Perhaps add a command switch `-C CACHE_DIR` to allow for another folder, and make it `env.cache_dir` instead of fixing it to `.sos`?

**Comment by BoPeng** [comment]
I dislike the idea of user specified directory and though of using something like `.sos/HASH` for a particular pipeline but then change of pipeline would invalidate the HASH...

**Comment by BoPeng** [comment]
Duplicate with #235
