### ISSUE TITLE
Can not link to html/png files under wiki.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#114]
I addded `QuickStart.sos	`, `QuickStart.sos.html`, and `QuickStart.sos.vim.png` under `SOS.wiki/tutorial` but cannot refer to them from [sos show](https://github.com/BoPeng/SOS/wiki/User-Interface#subcommand-show) page. Not sure what format the link should use.

**Comment by BoPeng** [comment]
Have to convert everything to png and link... this is not idea because we will need to use the same formats to present examples. I suppose in the end we will have to create a `examples` directory under the main git repository and refer to files there.

**Comment by gaow** [comment]
I'm not sure for html ... currently all PNG files are under `SOS.wiki/media` directory and can be used from wiki.

**Comment by BoPeng** [comment]
The problem is that we will need to use html examples. If you are not sure either, we can move examples to the example directory that I have created for the markdown branch. Not quite sure if it is easy to refer to html files there either though.

**Comment by gaow** [comment]
No it is not possible to properly display html from github.com; but we can put them to the gh-pages branch and use github.io to display it. HTML only works on github.io

**Comment by BoPeng** [comment]
Later then, I am tired now.

**Comment by gaow** [comment]
Yes it is a long day for you! Using gh-pages branch is actually quite easy so either of us can do it later: 

https://help.github.com/articles/creating-project-pages-manually

**Comment by BoPeng** [comment]
Thanks. The idea is to have a few good examples, put them and their html versions their for people to read. Right now github cannot syntax highlight sos script at all (I created a ticket for this).

**Comment by gaow** [comment]
I noticed you already have a branch `gh-pages` and a fancy `index.html` there ... not sure what is the plan but I guess we can re-purpose it for publishing examples.

**Comment by BoPeng** [comment]
I did? Then that must have been created during the play around time. You
can certainky repurpose.

**Comment by gaow** [comment]
Ok that explains the obsolete contents. The `index.html` looks nice, though, and we'll need an index page anyways for all the examples. I just do not have any clue how you generated that page from README.md back then. I guess I'll just move some examples there and hopefully you can recall how you generated index.html so that we can do it to index the examples. 

I moved your examples under `tutorial` on the wiki repo and under `examples` on the `markdown` branch to `examples` on the `gh-pages` branch. The PNG files under `tutorial` on wiki are moved to `media` where we keep docs, pictures and videos. 

http://bopeng.github.io/SOS/examples/QuickStart.sos.html

**Comment by BoPeng** [comment]
The last script in QuickStart.sos.html looks wrong so the HTML file must be generated using a wrong version. Since `--html` is still evolving, we can fix them altogether later.

**Comment by BoPeng** [comment]
I remember now that I used https://help.github.com/articles/creating-pages-with-the-automatic-generator/ to generate a website from README.md and a template. It would be great if we can do the same thing to the wiki, after all it is easier to edit documentation there.

**Comment by gaow** [comment]
I thought you once tried to port the wiki to readthedocs.org and I assume markdown is directly supported? I like that website better because of the side bar navigation.

**Comment by BoPeng** [comment]
I tried, the build process existed without error but I could not find the resulting webpage. I figured that we need to have sphinx install locally, tweak `conf.py` to generate html files before we try to port to `readthedocs.org`.

**Comment by gaow** [comment]
Github wiki, though simple, has its merits. If it is not that straightfoward to use readthedocs, I think we can stick to github wiki and vastly improve by refactoring the doc and create separate sidebars. We can discuss about a better structure later. Those HTML pages generated by SoS are separate pages anyways and will have to be referred to by links no matter how we do it. They can stay on github.io and be referred to from our wiki.

**Comment by BoPeng** [comment]
It should not be difficult to write a script to sync SOS.wiki to gh.pages and write a small script to generate Sphinx or other docs there... I will enlist someone else for these tasks if the grant is finalized.
