### ISSUE TITLE
Rscript interpreter option cause problems.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#116]
```
Failed to execute script. The script is saved to .sos/Rscript_2764.R. Please use command "Rscript --default-packages=methods,utils,stats .sos/Rscript_2764.R" to test it.
```

```
$ cat .sos/Rscript_2764.R
cars <- c(1, 3, 6, 4, 9)
pdf('test_plot.pdf')
barplot(cars)
dev.off()
```

```
$ Rscript .sos/Rscript_2764.R
null device
          1
```

```
$ Rscript --default-packages=methods,utils,stats .sos/Rscript_2764.R
Error: could not find function "pdf"
Execution halted
```

**Comment by gaow** [comment]
This is a pain. How is it resolved now? Another way to run R scripts is `R --slave --no-save --no-restore < script.R` where script comes from stdout. This might be a better solution because we can avoid writing script to file in `inline` mode.

**Comment by BoPeng** [comment]
Right now I simply remove the options (in the markdown branch). I will let you figure out how to properly do this because Matthew spent quite some time today on R stuff (seems unrelated?).

**Comment by gaow** [comment]
Haha, yes sure, I'll fix that. Nowadays Matthew is experimenting new styles to give talks -- with minimal formula, lots of graphs (ideally interactive graphs) and R examples. I find it intuitive and entertaining; the downside is that one will have to read into the paper before / after the talk to really learn from it ...

**Comment by BoPeng** [comment]
Even with his new style, I followed only half of his talk and got lost. I would have a better reception of statistical formulas 10 years ago, but not now. :-(

**Comment by gaow** [comment]
From what I recall about this talk, he motivated prior a lot but not other Bayesian parts particularly the inference. Instead he shows results. Maybe that's why it is hard to grasp on the spot because you'll have to fill big gaps ...

**Comment by BoPeng** [comment]
Is is published work, right? I could not recall a reference, do you have one?

**Comment by gaow** [comment]
Yes, here is a preprint: http://biorxiv.org/content/early/2016/01/29/038216

It will appear on Biostatistics or PLoS One (he only publishes to these 2 journals if it is single authored paper ...)

**Comment by gaow** [comment]
This works

```
Rscript --default-packages=methods,utils,stats,grDevices,graphics test.R
```
It is not possible to use `R ... < test.R` with the current ` SoS_ExecuteScript` which does not take scripts from stdin streams. We can keep adding things to `--default-packages` but we never know when it will be enough. that's why i always do `R ... < test.R` for R in command line.

I added those additional packages to Rscript command for now.

**Comment by BoPeng** [comment]
We do not yet have a mechanism to customized command line. I added `cmd {script}` stuff but reverted it because sometimes basename, sometimes directory have to be used.

**Comment by gaow** [comment]
Most likely, what we have included in `--default-packages` is sufficient. Because if you open up `R` and do:

```
> searchpaths()
[1] ".GlobalEnv"                             
[2] "/opt/miniconda3/lib/R/library/stats"    
[3] "/opt/miniconda3/lib/R/library/graphics" 
[4] "/opt/miniconda3/lib/R/library/grDevices"
[5] "/opt/miniconda3/lib/R/library/utils"    
[6] "/opt/miniconda3/lib/R/library/datasets" 
[7] "/opt/miniconda3/lib/R/library/methods"  
[8] "Autoloads"                              
[9] "/opt/miniconda3/lib64/R/library/base"   
> search()
[1] ".GlobalEnv"        "package:stats"     "package:graphics" 
[4] "package:grDevices" "package:utils"     "package:datasets" 
[7] "package:methods"   "Autoloads"         "package:base"     
> 
```
You see that we have loaded all the default search paths and packages.

**Comment by BoPeng** [comment]
This makes sense. Do you have any concern over the design of report facility in SoS (`!`, `report` and `pandoc`)? Otherwise I will merge the branch as long as it does not break any test. Other than some implementation details (when and where to save report etc), my biggest concern is how to help users report results in nice formats (e.g.  `kable` for `knitr`), but these are improvements for later and we can probably find some python packages for them.

**Comment by BoPeng** [comment]
Found https://pypi.python.org/pypi/tabulate

**Comment by gaow** [comment]
Sorry I'll take a look in a couple of ours and get back. I think if we can generate nice markdown format then users can organize results relatively easily. I recently adopted `bookdown` as a labnote (I have a python program to wrap it up). Combined with `DT`, and R package, tables can appear rather nicely:

https://bookdown.org/yihui/bookdown/html-widgets.html

Because they all take markdown file as input I think if we give reasonably good enough report in markdown users can do fancier things on top of it.

**Comment by BoPeng** [comment]
OK, we are not in the business of providing nice report.... 

But not everyone lives in R world and there are cases where we need to report results saved in .csv files, or if users use pandas in SOS and need to write report in markdown. Anyway, it seems to be user's repressibility to produce the right markdown code and we can at most document a few tips and tricks in our SoS reporting guide.

**Comment by gaow** [comment]
Even for people not using R, it is still possible to write plain Rmd file same as markdown file and use Rmarkdown to convert it. It just happens to be the case that R provides something that, for instance, can easily load CSV into Rmarkdown as nicely formatted, even dynamic tables with query options. I agree it is sufficient to just document those tricks. My point was that it was perhaps better to leverage rmarkdown than to try to improve `report()` action via pure efforts in python coding.

**Comment by BoPeng** [comment]
`iris` does not exist... so we really need to fix this `Rscript` business.

**Comment by BoPeng** [comment]
It appears that `dataset` is the only one that is missing. I have added it.
