### ISSUE TITLE
Extend the functionality of 'group_by="pairs"'

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#123]
Currently `pairs` only allows for 2 files to combine. I have a situation where I need multiple files to form a group, e.g., 3 files at a time. I'm wondering if we can extend `pairs` to 

```
group_by='pairs_N'
```
Where `_N` means N files in a group. Default N = 2 and `group_by='pairs_2'` is equivalent to `group_by='pairs'`.

Thanks a lot!

**Comment by BoPeng** [comment]
The existing implementation pairs 

```
1 2 3 4
5 6 7 8
```

to `[1,5]`, `[2,6]`, `[3,7]`, and `[4,8]`

This is ok, but for `pair_4`, it would like

```
1 2
3 4
5 6
7 8
```

to `[1,3,5,7]`, `[2,4,6,8]`, which less intuitive than `[1,2,3,4]`, `[5,6,7,8]`.

Note the `pairs` is designed for

```
input: 
    sorted(x for x in fastq_files if 'R1' in x),
    sorted(x for x in fastq_files if 'R2' in x),
    group_by='pairs'
```

**Comment by BoPeng** [comment]
A better syntax should be

```
input: group_by='trunk_4'
```
or
```
input: group_by=trunk(4)
```

if we can get it work that way.

**Comment by gaow** [comment]
I agree it would be more intuitive to have things like `[1,2,3,4], [5,6,7,8]` and use a new syntax. Do you meant to say `chunk`? Perhaps `block` is another option. Also the quotes are required, so should it be `group_by='trunk(4)'`? I'm neutral to `_` vs `()`, though.

**Comment by BoPeng** [comment]
How about group_by=3?

**Comment by gaow** [comment]
Ha that works perfectly!

**Comment by BoPeng** [comment]
I am away from my computer but you should be able to implement it without
much trouble. Do not forget documentation. We could also allow '3' for
consistency in datatype, you decide.

**Comment by gaow** [comment]
Yes I can document it then. I think 3 without quote is good. '3' looks more like a keyword but here it is not a keyword, but rather a mechanism.

**Comment by BoPeng** [comment]
Still working on it?

**Comment by gaow** [comment]
Oh sorry I misread your message ... I'll do it tomorrow then -- still trying to wrap up some work before the day ends (hopefully soon!).

**Comment by BoPeng** [comment]
Fixed.
