### ISSUE TITLE
checking syntax before the execution of R script.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#130]
Recent patches add features that

1. check interpreter for any script-executing actions at dryrun mode
2. check the syntax of scripts at prepare mode. This is done by

 * for python3, try to compile
 * `perl -c script` to check syntax of perl
 * `bash -n script` for bash, similar syntax for sh, tcsh, zsh etc
 * `python -m py_compile script.py` for python
 * `ruby -c filename.rb` for ruby

What is the proper command to check R script?

**Comment by gaow** [comment]
I'm not aware of one, and my google search did not give one either. Let me ask around, though I'm not surprised if R does not have it.

**Comment by gaow** [comment]
So there is a package(!!) for the job:
https://github.com/jimhester/lintr
Again, typical!

**Comment by BoPeng** [comment]
So the command line is?

```
Rscript .... lint("script.R")
```

Please see if you can fit this in a command,...

```
 validate_with_command('/bin/bash -n')
```

or write a separate validation function, which accepts script and filename, and raise an exception with messages on error.

**Comment by gaow** [comment]
Yes I  will check it later this evening.Away from computer now.  But firstly do you mind having to install this pkg for this feature? What if install fails due to eg no internet? Do we insist on checking?

**Comment by BoPeng** [comment]
If it is easy to install (`check_R_library('lint')` can take care of it), we can install it on the fly. Otherwise we can make it optional, namely using it if the package exists (but we need to check if the library exist, which can be troublesome).
 
I think it is important to detect errors early (during preparation) and with proper error message so that users can fix scripts before they run anything. This is especially important because users cannot see the complete script and cannot test them with all the `${}`s. I have therefore try to output interpolated scripts during preparation stage (to `.sos/step_name.suffix`) and check for syntax errors on then. Users can also grab these expanded scripts and test them (e.g. in RStudio). I have found this feature extremely helpful to write my .sos script today, although this feature ate most of my time.

**Comment by gaow** [comment]
I agree it is going to be very helpful! I noticed currently the problematic scripts are saved to .sos which is already very handy. Installation should be easy with internet. I just worry about it when there's not.

**Comment by BoPeng** [comment]
It is not too harsh to require this library when we see r script. You can see that right now action r will check r at dryrun, we can check lint at dryrun or prepare.

**Comment by gaow** [comment]
Ugly, but should do the trick: 84fa949365369069529cf181acf91bf49ec18a36

**Comment by BoPeng** [comment]
Close for now.

**Comment by gaow** [comment]
Because we force install `lintr` for syntax check and it is likely installation fails, I'd get this ugly message every time I run SoS:

```

WARNING: Syntax error found in script /home/gaow/GIT/dr-tree/analysis/.sos/SimulateTree_1.R:
also installing the dependencies ‘lazyeval’, ‘praise’, ‘formatR’, ‘highr’, ‘markdown’, ‘yaml’, ‘rex’, ‘crayon’, ‘stringdist’, ‘testthat’, ‘knitr’

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("lintr", repos = "http://cran.us.r-project.org",  :
  installation of package ‘stringdist’ had non-zero exit status
2: In install.packages("lintr", repos = "http://cran.us.r-project.org",  :
  installation of package ‘lintr’ had non-zero exit status
Error in loadNamespace(name) : there is no package called ‘lintr’
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

WARNING: Syntax error found in script /home/gaow/GIT/dr-tree/analysis/.sos/SimulateTree_1.R:
also installing the dependency ‘stringdist’

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("lintr", repos = "http://cran.us.r-project.org",  :
  installation of package ‘stringdist’ had non-zero exit status
2: In install.packages("lintr", repos = "http://cran.us.r-project.org",  :
  installation of package ‘lintr’ had non-zero exit status
Error in loadNamespace(name) : there is no package called ‘lintr’
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```
Shall we be less progressive about this and only check R syntax if `lintr` is installed (quite the check command if package not found)? Package installation with R is not trivial and can fail very often. Sometimes in order to get one packages installed (`lintr` and its dependencies this case), one may have to break other packages. I'm sure many R users would rather not check the syntax up-front than wrestling to get `lintr` installed.

**Comment by BoPeng** [comment]
You mean installation of `lintr` on the fly can fail? If so, we should of course make it optional.

**Comment by gaow** [comment]
Oh yes, unlike `pip install` which almost never fails, I experience more failures auto-installing R packages than success -- partially because I use R from conda (a rather buggy R bundle though convenience), partially because I had to tweak my R for some packages to install which in turn break others. R is painful to work with outside RStudio.

**Comment by BoPeng** [comment]
If should be easy to check our miniscript, right? I will leave this to you.

**Comment by gaow** [comment]
Sure -- I'd change the behavior to quit if `lintr` is not found, without attempting to install it, and give a warning at SoS level saying that users need to install `lintr` to enable R script syntax check. Is this fine?

**Comment by BoPeng** [comment]
Then the warning will be displayed again and again, right? I am not sure if that is a good idea. Perhaps it is enough to document that SoS will use `lintr` if it is installed.

**Comment by gaow** [comment]
Agreed.
