### ISSUE TITLE
Behavior of ${output} 

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#132]
I have a script that previously works but is no longer the case. I suspect it is related to the recent change of output behavior where they became accessible early on. So my problem is as follows:

```
[default]
n = [1000]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
output_files = ['{}.rds'.format(x) for x in range(10)]
input: for_each = ['n', 'seed']
output: output_files[_index]
run:
echo ${output}
touch ${output}
```

You see even though here we use a loop I expect every time I call `${output}` the entire output (for 10 files) is generated. But it is not the case. The outcome for that script is:

```
0.rds
0.rds 1.rds
0.rds 1.rds 2.rds
0.rds 1.rds 2.rds 3.rds
0.rds 1.rds 2.rds 3.rds 4.rds
0.rds 1.rds 2.rds 3.rds 4.rds 5.rds
0.rds 1.rds 2.rds 3.rds 4.rds 5.rds 6.rds
0.rds 1.rds 2.rds 3.rds 4.rds 5.rds 6.rds 7.rds
0.rds 1.rds 2.rds 3.rds 4.rds 5.rds 6.rds 7.rds 8.rds
0.rds 1.rds 2.rds 3.rds 4.rds 5.rds 6.rds 7.rds 8.rds 9.rds
```
This is unexpected behavior that perhaps should be considered bug ...

**Comment by BoPeng** [comment]
It is a bug...

**Comment by BoPeng** [comment]
However, if you look at https://github.com/BoPeng/SOS/issues/111 , the behavior will return if I implement the separation of task and action... In that case, without `task`, the `output` will be incremental within the action. 

Then it is logically strange if the introducing of `task` before `run` actually change the definition of `output` used by `run`.

**Comment by BoPeng** [comment]
Should be fixed, but the behavior might need to be re-considered.

**Comment by gaow** [comment]
Yes I confirm that my old script is working again.

Is #111 officially implemented as proposed? I remember we had `process` keyword before so I'm a bit confused what's the difference between that and `task`

**Comment by BoPeng** [comment]
The process keyword has been replaced by task (you might missed the ticket) because

1. step process is the complete process executed by SoS, including all the python statements.
2. task is part or all of the process that will be executed and monitored externally

The name task is more consistent with its nature because process usually refers to local process.

Issue #111 is concerned with whether or not we should by default make the script form of actions a task, because currently

```
run:
  script
```

is different rom

```
run(script)
```

because the former is

```
task:
run(script)
```

and I now tend to make the syntax more consistent..

**Comment by gaow** [comment]
I have a question which I'm not sure if it is relevant to #111. Essentially what I want is to have 2 actions in one SoS step, the first action uses single process and output some "overall" information; the 2nd action is `concurrent` and works on each loop. For example (not valid syntax but illustrates my intention):

```
[default]
n = [1000]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
output_files = ['{}.rds'.format(x) for x in range(10)]
input: for_each = ['n', 'seed']
output: output_files[_index]
run:
echo ${output}
run: concurrent = True
dosomething ${_seed} ${_n} ${_output}
```
Can this be achieved with the current behavior of SoS task?

**Comment by BoPeng** [comment]
You are asking for something like:

```
[default]
n = [1000]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
output_files = ['{}.rds'.format(x) for x in range(10)]
input: for_each = ['n', 'seed']
output: output_files[_index]
if _index == 0:
  run('echo ${output}')
run: concurrent = True
dosomething ${_seed} ${_n} ${_output}
```

so it is possible to do it within the current framework. This is actually related to a previous discussion where we would like to have 

```
[10]
input: for_each
run:
   several jobs

report:  ???
   only once after the job is done.
```

I suppose something like

```
[10]
input: for_each
run:
   several jobs

report:  skip=_index ??
   only once after the job is done.
```
would work.

**Comment by gaow** [comment]
Great, right, this is also related to #99 where I commented on `_index` being not very explicit. It is infrequent that we do something special for _index other than the first and last. I wonder if providing some action options to indicate execution only at the first or last _index is sufficient.

**Comment by BoPeng** [comment]
Need a good name/syntax... perhaps?

```
active=0
active=-1
```

**Comment by gaow** [comment]
So if we still implicitly assumes some indexing, how about also make slicing possible:
```
on = 0 # active for only first step
on = [0::2] # active for only even index
on = [1::2] # for odd index
on = -1
on = [:-1]
```

And we can have `off` which behaves the opposite.

**Comment by BoPeng** [comment]
This should be easily achieved... and you like `on` better than `active`?

**Comment by gaow** [comment]
> you like on better than active?

Not necessarily. I was more thinking about `on/off` being a pair. But I assume `active/inactive` can also be a pair, though `inactive` reads a bit passive.

**Comment by gaow** [comment]
So in that case I can also do it at the last _index:

```
[default]
n = [1000]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
output_files = ['{}.rds'.format(x) for x in range(10)]
input: for_each = ['n', 'seed']
output: output_files[_index]

run: concurrent = True, off = -1
dosomething ${_seed} ${_n} ${_output}
run: on = -1
doanotherthing ${output}'
```

From what I understand I cannot reset `concurrent` in the 2nd `run` action, which I would set it to `False`, with current syntax. It does not matter either way in this case, though.

**Comment by BoPeng** [comment]
I am separating script format with task directive... with argument in #133 . Sorry to break your code.

**Comment by gaow** [comment]
Oh its Ok, if it is ongoing. There seems more pros than cons so we should go for it. I'll update my codes when it is settled.

**Comment by gaow** [comment]
Just for a record, 

```
if _index == 0:
  run('echo ${output}')
```
does not work because it again produces:
```
0.rds
0.rds 1.rds
0.rds 1.rds 2.rds
0.rds 1.rds 2.rds 3.rds
0.rds 1.rds 2.rds 3.rds 4.rds
0.rds 1.rds 2.rds 3.rds 4.rds 5.rds
0.rds 1.rds 2.rds 3.rds 4.rds 5.rds 6.rds
0.rds 1.rds 2.rds 3.rds 4.rds 5.rds 6.rds 7.rds
0.rds 1.rds 2.rds 3.rds 4.rds 5.rds 6.rds 7.rds 8.rds
0.rds 1.rds 2.rds 3.rds 4.rds 5.rds 6.rds 7.rds 8.rds 9.rds
```

**Comment by BoPeng** [comment]
I have continued to think about this problem and I believe that the meaning of `output` should not differ between

```
[10]
input:   
output:  _input[0] + '.bak'
action(output)
```

and 

```
[10]
input:   
output:  _input[0] + '.bak'
task:
action(output)
```

Can we just adopt the accumulative output idiom? That is to say,

1. `output` will be the accumulative version of `_output`, but only if `_output` changes during loop.
2. task only specifies the rest of the step process will be executed externally through a task manager/worker system.

A special case is that if we have

`_output=a, a`, and `b, b` 

we should have

`output=a`
`output=a`
`output=a, b`
`output=a, b`

Another choice is to have

`output=a`
`output=a a`
`output=a a b b`

but we will have a hard time to handle the case of `a a a a`, in which case we should have

`output=a`
`output=a`
`output=a`
`output=a`

**Comment by gaow** [comment]
I'm Ok with `output` being cumulative as long as it is possible to get the complete output via:
```
run: active=-1
echo ${output}
```
I mean it makes sense to accumulate `output` in a loop but the final output should agree with the whole set.

I think if `_output` is `a, a, a, a` we should have `output = a a a a`. Again the point is that if the `a a a a` sequence is intentionally designed and is desired to feed to the next step as `input` as is, then messing with the `output` under the hood (removing dups) will cause confusions.

**Comment by BoPeng** [comment]
Output option dedup=true?

**Comment by gaow** [comment]
I could not think of a better idea then, and still no, after a night :( After all it would be good to have an additional option than having nothing to allow for both possibilities. 

Thanks a lot!

**Comment by BoPeng** [comment]
The change is not easy. The biggest problem is that we rely on 'statements before task' when `output` should be available to check if tasks can be skipped. The correct way to do this is to perform signature check in dryrun/prepare mode and skip the execution in run mode, which is the job of a DAG.

I also found quite a few problems with the new features (report, ipython, jupyter etc) and tried to make them more usable yesterday. After all, we moved a bit too fast on those features.

**Comment by BoPeng** [comment]
I am going to implement option `dedup`, right now with only `output:` as

1. `dedup=True` by default
2. `dedup=True` enables the previous behavior, that is to say, all files are appended gradually, but duplicated files are removed with order preserved. That is to say, even without loop, `a b a` would result in `a b`. I guess we can produce an warning if `len(output) < len(_output)`.
3. `dedup=False` goes another extreme, that is to say all output files are appended even with identical `_output`. That is to say, with loop and `output: a b`, we will get `output=a b a b a b`.

**Comment by BoPeng** [comment]
Fixed.
