### ISSUE TITLE
sos show or sos view

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#134]
```
sos show script --html/--markdown/--term
```

is **viewing** the same item with different views so `sos view` sounds like a better command name. Not a big deal but I have found myself tying `sos view` a few times.

**Comment by gaow** [comment]
`view` +1

**Comment by BoPeng** [comment]
But the default `sos show` does not view in the sense that it represents an organized (and simplified) version of the script...

**Comment by BoPeng** [comment]
Also view sounds formal/robotic/distant and show is more personal, with passion. I rarely use view as a verb because of it.

**Comment by BoPeng** [comment]
Actually, when you think of it, our `dryrun` should be better called `inspect` because `prepare` also runs the script, with even more detail, and this `dryrun` steps simply check syntax error if we do not build DAG at this stage.

**Comment by gaow** [comment]
Now that we do check syntax of embedded script, inspect sounds proper. Also
the word drillrun popped on my mind though it is not a real English word

**Comment by BoPeng** [comment]
Just replaced dryrun with inspect. `check` is also a good word and is used more frequently, but option `-c` has been used for `config`.

**Comment by BoPeng** [comment]
Both commands are supported (`show` is now an alias to `view`), we can decide this later or keep both. I have also added `dryrun` and option `-d` back for backward compatibility.

We are at alpha so backward compatibility is not required. However a bit time plus a warning message before removing a feature can be nice.

**Comment by gaow** [comment]
It's nice to be backward compatible but perhaps it only worth the trouble after publication ... A colleague of mine was asking me to give him a jump start on snakemake today. I tried to sell SoS to him but he said his mentor asked him to use snakemake and it is readily available on the cluster (he does not know how to install packages locally and is too busy to learn) :(

**Comment by gaow** [comment]
Oh with that sale: I brought up the interactive SoS programming and that did not help ... I can imaging for the R camp anything outside Rstudio is foreign territory, particularly something in a different programming language that seems to overlap a lot with Rstudio is considered pagan. I'm curious how bioinformaticians will receive this selling point. There are few bioinformaticians around me though.

**Comment by BoPeng** [comment]
BTW, the `view/show` brothers now have another sibling called `convert`, which is likely to stay...
