### ISSUE TITLE
Interactive use/debug of SoS scripts in ipython

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#135]
If we can teach ipython SoS string interpolation through some plugin, it would allow users to play with SoS expressions, even evaluate a trunk of expressions there. Right now users cannot do much with a bunch of strings containing `${ }`.

**Comment by BoPeng** [comment]
This is so cool

```
[bpeng1@bcbm-bpeng:~]$ ipython
Python 3.5.1 |Anaconda 2.5.0 (x86_64)| (default, Dec  7 2015, 11:24:55)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.3 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

[TerminalIPythonApp] Loading IPython extension: storemagic
[TerminalIPythonApp] Loading IPython extension: autoreload
[TerminalIPythonApp] Loading IPython extension: sos_magic

In [1]: sos a=1

In [2]: sos '${a+1}'
Out[2]: '2'

```

**Comment by gaow** [comment]
Indeed! Is this just for playing with SoS syntax? If that's the case, what might be even cooler is to host a ipython notebook that already loads the plugin and direct users to play over there. I am just not sure where we can find a reliable free notebook server to use long term.

**Comment by BoPeng** [comment]
It can be a lot more than that, say

* `sos_run` that runs a step or a piece of sos script.
* `sos_runpaste` or `runpaste` to run currently selected sos script
* `dryrun` that dryruns
* `prepare` that prepares
* `dryrunpaste` that dryruns selected
* `preparepaste` that prepare selected
* `sos_dict` to show dictionary (sos current state)
* `sos_vars` show a list of vars without values
* `sos expr` (already implemented) so a variable or result of an expression
...

In the end, ipython stores a SoS_dict and we constantly send pieces of SoS script to it. Say I have a step of R code that just does not run well, I can modify it and send it to ipython repeatedly, which is much better than save the script and rerun `sos run script.sos` from command line.

**Comment by BoPeng** [comment]
A quick tutorial is at https://github.com/BoPeng/SOS/wiki/Interactive-SoS before all magics are implemented.

**Comment by BoPeng** [comment]
More magics are added and documented at the tutorial. `preparepaste` etc are not needed because we can pass command line arguments to the workflow from ipython. Everything works beyond my expectation and I am happy that I can finally debug SoS scripts interactively.

Try it out and let me know if you have any suggestion.

**Comment by gaow** [comment]
This reads great! I did not see a comprehensive list of available magic keywords on that tutorial page, though, like you have listed above. Are they documented elsewhere?

**Comment by BoPeng** [comment]
Note that you should read the tutorial updated this morning not yesterday
night.

Sent from my cellphone
On May 4, 2016 10:32 AM, ben.bob@gmail.com wrote:

We only have four and I am thinking of removing one more. The ability to
use command line options greatly reduced the need for more magic.

Sent from my cellphone
On May 4, 2016 9:56 AM, "gaow" <notifications@github.com> wrote:

This reads great! I did not see a comprehensive list of available magic
keywords on that tutorial page, though, like you have listed above. Are
they documented elsewhere?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/BoPeng/SOS/issues/135#issuecomment-216891120>

**Comment by BoPeng** [comment]
We only have four and I am thinking of removing one more. The ability to
use command line options greatly reduced the need for more magic.

**Comment by BoPeng** [comment]
By removing one more magic I meant to change

```
%sosreset
```

to

```
%sosdict reset
```

and allow more options such as

```
%sosdict keys
```

to return keys

```
%sosdict new
```

by new I meant the dictionary item that is not part of SoS and are introduced by the execution of workflows.

**Comment by BoPeng** [comment]
This is done. Please check the updated tutorial. I like the default behavior because we can check variables without all the sos items. This makes `%sosdict` a lot more useful.
