### ISSUE TITLE
Behavior of ${input}

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#137]
This should also be related to my latest comment on #132: 

```
[1]
output: '1.txt'
run:
touch ${output}

[2]
input_files = ['1.txt' for x in range(5)]
input: input_files
run:
echo ${input}
```
You should expect the outcome being 
```
1.txt 1.txt 1.txt 1.txt 1.txt
```
But instead I still get 
```
1.txt
```
Basically here I overwrite the default input but it looks like the information was not updated.

**Comment by BoPeng** [comment]
This is by design (but can be changed probably). If you use `-v3`, you will see that `input_files` are taken, and you do have `_input` correctly. However, `input` is collected from `_groups` as follows

```
            env.sos_dict.set('input', list(OrderedDict.fromkeys(sum(self._groups, []))))
```

The reason is that some `_input` can be ignored (`skip`) and filtered (`'filetype`) and `input` is set to the remaining unique files.

**Comment by gaow** [comment]
Yes I realized the `_input` is good (that's why I did not tag it bug this time). You probably have good reason for this behavior ... Although I can bypass it in my application, I'm just trying to find justification from user's prospective on this behavior. Currently it seems a bit confusing.

**Comment by BoPeng** [comment]
We can at least give a warning about repetitive filenames...

**Comment by gaow** [comment]
Sometimes repetitive filenames are intentional. For example in my case, I do something like [(a.txt, A.txt), (a.txt, B.txt) (b.txt C.txt) (b.txt D.txt)] so a.txt and b.txt are repetitive but desired.

**Comment by gaow** [comment]
Also, although I can possibly customize my input by calling `${_input_files}` instead of `${_input}` in my application, I still feel worried because the `output` also comes from `set`: duplicates removed and ordering not preserved. We would expect neither of this when we use, by default, the output from previous step as the input of the next step. So it is likely to break a pipeline.

I agree that `skip` or filter should be taken into account, and from the surface it does not seem conflicting to keeping the order and possible duplicates. Are there any harms to change the behavior?

**Comment by BoPeng** [comment]
At least the order is kept.

**Comment by gaow** [comment]
Oh ok i should have realized OrderedDict must be doing something there. Still, removing duplicates may break a pipeline where the output of a step is a carefully crafted sequence containing duplicates.

**Comment by BoPeng** [comment]
Ok, I figured removing duplicate filenames was necessary. I have submitted a patch to use 'filetype' filtered input files as input. The skipped groups are not considered, which makes sense anyway because they are part of input, but are not processed.

**Comment by BoPeng** [comment]
BTW, I am testing the change by selecting the script in browser, and typing `sospaste` from ipython. It is much faster than creating a `test.sos`, copy/paste content there, and run `sos run test.sos` from command line.

**Comment by gaow** [comment]
I was trying to use it yesterday but had some issues with my ipython so I'll have to reinstall conda today and give it a go ...
