### ISSUE TITLE
Display failed scripts on screen

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#142]
Currently when error occurs, the entire failed script is printed to screen. This may be informative for commands but is rather distracting for long scripts. Also when a step has multiple `run` yet only one of them fail, then all scripts will be displayed. I think it is Ok that we stop printing them, because SoS creates `.sos/<script_name>` for failed scripts anyways, it is not necessary to print anything on the screen. Without it, the last line of hint to the diagnostic script will also stand out.

**Comment by BoPeng** [comment]
Done. Whole script replaced with `shortRepr`.

**Comment by gaow** [comment]
I trimmed it a bit more here: 4acd8db1d71b7fe91de6c7aae5de64a41c967393, hopefully this is legitimate.
