### ISSUE TITLE
A docker container with SoS

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#144]
Perhaps also with a Jupyter server. It should be good enough to start from anaconda 3 docker image.

**Comment by gaow** [comment]
I was under the impression the idea of docker image will not work due to the nature of SoS. Isn't that still the case?

**Comment by BoPeng** [comment]
This is not about sos install itself into a docker etc ( #87 ), it is simply a docker with python 3, sos, ipython , R, irkernel etc. SoS is easy to install but I have found irkernel etc are difficult to install.

**Comment by BoPeng** [comment]
The base image is called `mdabioinfo/sos:latest` and the complete one is called `mdabioinfo/sos-full:latest` (with IRKernel)

**Comment by BoPeng** [comment]
The containers need to be tested though.
