### ISSUE TITLE
Rename input pattern to extract, and output pattern to expand.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#152]
```
samples = [1, 2, 3, 4]
input: pattern='{samples}.txt'
```

The problem here is that `pattern` in `input` and `output` are doing completely different things but were given the same name. Perhaps we should name the output pattern as `expand`, and rename input `pattern` as `extract`. We can keep `expand` in `input` but its meaning would be identical to this parameter in `output`.

**Comment by BoPeng** [comment]
https://github.com/BoPeng/SOS/commit/3b623fbeca9eeedabf1afb195f9f564c86493dac 

I know you use `pattern` a lot. Hope this change makes sense to you.

**Comment by gaow** [comment]
Yes it does make sense and it is nice that pattern is still supported with a warning message :) Thanks!

**Comment by gaow** [comment]
So just to confirm here: we have `expand=...` in `output:` to use directly, and we still keep the utility function `expand_pattern()` in `output:` for more flexible usages, right?

**Comment by BoPeng** [comment]
yes, but I am thinking of changing it further after we have both `expand=` and `expand_pattern()`. You see, conceptually speaking, we have

```
expression to generation file names, options to work on them
```

and now we have

```
expand='pattern' 
```
to generate filenames. I would much rather have

```
expand('pattern'), options
```
to keep this concept. The latter is also clear if `expand='pattern'` should override default input. With the expression (function) form, it is clear that it will replace (just like if we add a filename), but users can do

```
input: myfilename, expand('pattern')
```
if they really want to extend another list.

**Comment by BoPeng** [comment]
So in the end we might

1. keep input option `pattern`, or rename it to `extract`
2. replace input and output option `expand` with function `expand` or `expand_pattern`. `expand` sounds better but it has an bigger chance of conflicting with user code.

**Comment by gaow** [comment]
Yes that makes it more clear indeed. Perhaps `pattern` for input and and `expand_pattern` for output is best, because `pattern` sounds more intuitive than `extract` and as you said `expand` alone may conflict user's codes.

**Comment by BoPeng** [comment]
ok, then compared to previous behavior, we just

1. keep input `pattern`
2. remove output option `pattern` and force the use of `expand_pattern`.

**Comment by gaow** [comment]
Sounds fantastic :)

**Comment by BoPeng** [comment]
Done.
