### ISSUE TITLE
Revisit the implicit input file design.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#155]
It is practically impossible to use implicit input files in interactive mode because enter `enter` will trigger an empty step, and clear the previous output. This makes `__step_output__` a mysterious object and often cannot be used. I have therefore used explicit input all the time in interactive mode. Even in the batch mode, when the workflow gets complex, it can be difficult to track the "previous" step and figure out what would be the input of a step. 

The problem with explicit input is however the loss of flexibility for input files because we have to use either fixed filenames or variables .... However, say if we use variable `bamfiles` as input of a step, we have to define this name to use the step, which 

1. makes it difficult to re-user steps because we have to use names specified by the steps
2. even with such names, there is no guarantee the content of that variable...

For example, right now we can control what a step or nested workflow does by specifying `__step_output__` and do not care how the step treats this variable (take a ignore). We will have to know what a step requires if we require explicit input...

**Comment by gaow** [comment]
I'm under the impression that implicit input is only completely implicit for auxiliary steps. It is semi-implicit for other steps because the input is by default the output of the previous. For semi-implicit it looks straightforward to track the previous step because it's just the immediate upstream step in the workflow sequence, right? I think it works very well the way it is but may be I'm not getting the problem here ...

**Comment by BoPeng** [comment]
The problem comes from my frustration to run sos interactively, for which the **last step** is elusive because the steps are unordered and are executed in random order. It is therefore necessary to use explicit variables for input/output files.

Even for script style use, the ability for one section to be shared by multiple workflows (`a_1,b_10`), by different nested workflows (`sos_run('a_1`)`), ignored by logic (`skip=command_line_option`) or from command line (`workflow_4-`), used by multiple steps in the same workflow (`a_10,a_20`), used by  make-style rules (`provides`) will make the logic order of execution unclear. ... Using explicit input does not really help though.

**Comment by gaow** [comment]
I see. For shared steps in script style I just assign alias and use that later. I also use nested workflows a lot to build different versions of pipelines. I found these two features very helpful.

**Comment by BoPeng** [comment]
Whereas I have had some success in using sos for my daily work, I had to spend a lot of time fixing small problems and making things clearer (e.g. more prompt output, report, transcript etc). Hopefully over time there would be less surprises and confusions.

**Comment by gaow** [comment]
I guess it's great power comes greater responsibility :)

I'm finally starting to do some exploratory analysis that I think it is good time to take advantage of SoS Jupyter. Is it correct to assume that moving on to Jupyter I should totally give up ipython (whatever available with ipython is now in Jupyter?) ? All I have to read is the tutorial, the example (both in notebook format) and [this section of documentation](https://github.com/BoPeng/SOS/wiki/Interactive-SOS#using-sos-with-jupyter-notebook), right? Thank you!

**Comment by BoPeng** [comment]
The jupyter notebook is broken by accident. Let me fix it now.

**Comment by BoPeng** [comment]
Depend on the way you work, you can use 

1. `ipython --profile sos` with mixed python, shell and sos.
2. `jupyter qtconsole --kernel sos` to accept and run pieces of code sent from emacs/vim. I have made the vim-ipython more or less usable, but you will not use it if you use emacs.
3. `jupyter notebook` to use it as the main format and editor.

I have been switching between these methods to get a feeling of how they should be used. You can try and let me know what you think.

**Comment by BoPeng** [comment]
There is at least one thing can be done, namely do not change step input and output if no `input:` and `output:` is specified in a step (e.g. in a normal expression cell).

**Comment by BoPeng** [comment]
Stop passing `__step_output__` to next executed cell because the cells are not steps and are not necessarily logically connected.  See https://github.com/BoPeng/SOS/commit/67cd0279701a81de6c0eb7d655ca9b67d72c2d81
