### ISSUE TITLE
sos notebook with pandas

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#157]
I am running into a weird issue which I eventually figured it is perhaps SoS to blame. I have made a minimal reproducible example here.

[test.zip](https://github.com/BoPeng/SOS/files/282595/test.zip)

There are 3 files: a data-set, a sos notebook and a python3 notebook. The codes between the notebooks are exactly the same only using different kernels. There was no issue running that python3 notebook (meaning my code is good) but with the SoS notebook the last step results in a pandas error: 

```
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```
And whatever commands you type after will always repeat this same error, e.g.

```python
1+1
```
```
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```
unless I restart the kernel. It looks tricky to me. Hopefully there is a happy solution.

**Comment by BoPeng** [comment]
I think I fixed these before. Let me have a look.

**Comment by gaow** [comment]
Great! For now I just have to use `%use python` to switch the channel and it works that way.

**Comment by BoPeng** [comment]
Should be fixed now. I handled 1-d case but pandas has 2-d... The code is for detecting readonly variables in sos (most of them should be) that should perhaps be removed for interactive mode.

**Comment by gaow** [comment]
Great! But keep it here is useful at least for debugging because we may feed crazy input in interactive mode and that's like a stress-testing that helps improving although other users might find it a bit upset when they run into issues.
