### ISSUE TITLE
Jupyter kernel with R

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#159]
I was tripped on this issue for quite a while until I realized it is again SoS kernel to blame. I have this data set: 

[data.rds.txt](https://github.com/BoPeng/SOS/files/283094/data.rds.txt)

(Please rename the file to `data.rds` after you download). I run these commands in SoS notebook
```
%use R
dat = readRDS("data.rds")
dat = as.matrix(dat)
head(rbind(diag(ncol(dat)),dat))
```
It shows `NA` for the rows that I bind. However if I start an R notebook and run the same 3 lines, I get what I expect. Not sure what's going on here. I assume with %use R that cell will switch to R kernel which should be the same as running an R notebook?

**Comment by gaow** [comment]
Hold on ... if I start a fresh SoS notebook and only run these lines it work. So you'll not be able to reproduce my example. This is rather weird, too! I'll dig further and update .

**Comment by BoPeng** [comment]
It looks like you have changed the variable in some previous R command ... did you try

```
rm(list=ls())
```
or
```
%restart R
```

**Comment by gaow** [comment]
Geez indeed %restart R works. This is very counter intuitive, though, because I did re-assign values to the data! Jupyter is kind of messy. I find myself doing `sos convert` all the time just to tidy things up!!

**Comment by BoPeng** [comment]
It can be R's problem, who knows... perhaps you can learn to stay more in jupyter.
