### ISSUE TITLE
Convert to notebook eats the last line of input

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#160]
For example I have this SoS script:

```
[GW] cat test.sos 
#cell code 1
a = 1
#cell code 2
b = 2
```
and I run `sos convert test.sos --notebook test.ipynb` then the last line is missing. Previously the last line exported from ipynb is an empty `#cell code` which I just removed from my previous patch. But this makes converting the other way around buggy. Was that intentional?

**Comment by BoPeng** [comment]
If the last line is missing, it is a bug on the `convert sos --notebook` side, let us worry about it later.

**Comment by BoPeng** [comment]
This is fixed now.

**Comment by gaow** [comment]
Looking good!

**Comment by BoPeng** [comment]
spyder has a concept of cell and uses the following syntax. We should use one of these syntax so that we can edit ,ipynb exported .sos file directly in spyder.

```
CELL_LANGUAGES = {'Python': ('#%%', '# %%', '# <codecell>', '# In[')}
```

**Comment by BoPeng** [comment]
Changed to use `#%%`
