### ISSUE TITLE
Unify section and cell header

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#167]
Although not well-thought-out, there is a possibility to unify SoS section with Jupyter cells by using the same kind of format ... 

Note that in spyder, if we enter

```
#%% 
```

spyder helps us define sections, and it also has a concept of Run cell, which is exactly what we need.  We can of course patch spyder to follow our syntax though, 

The problem with merging is that although spyder can live with parameters after `#%%`, jupyter does not accept parameters so we do not know what to do with the parameters when we convert from `.sosnb` to `.ipynb`. The only solution here is to separate the parameters from section head, doing something like

```
$%%
section: name='human_19', alias='blah'
```

which is worse than

```
$%%
[human_19, alias='blah']
```

**Comment by BoPeng** [comment]
Perhaps we can enforce the 

```
#%% 
```

format for `.sosnb`. 

Section headers have the format:

```
[workflow_idx: skip, alias, sigil, target]
```

except for `sigil`, all other information specifies how the sections will be called (in batch mode) and has no effect in interactive mode. It is therefore safe to say that section headers are not needed in notebook mode.

We are allowing the use of `[header]` in interactive mode, not sure if it is a good idea to disallow it.

**Comment by BoPeng** [comment]
I am still not sure if adding a separate `.sosnb` format is a good idea because of the need for extra documentation and conversion processes (e.g. `sos convert a.sos --sosnb`, `sos convert a.ipynb --sos`, `sos convert a.ipynb --sosnb`, `sos convert a.sosnb --sos`). 

I suppose we can use a single format and

1. Make `#%%` optional syntax for cell separation.
2. Provide options to add/remove `#%%`, e.g. `sos convert a.sos --define-cell --inplace`, `sos convert a.sos --remove-cell --inplace`.
3. Provide an option to execute `.ipynb` and `.sos` in interactive mode (e.g. run cells one by one). Jupyter seems to provide such a feature with more detailed documented in http://tritemio.github.io/smbits/2016/01/02/execute-notebooks/. I am not sure how well it works with all the sos magic though.

**Comment by BoPeng** [comment]
Because sos format can accept `#%%` lines, we do not have to enforce format differences between `.sosnb` and `.sos` files. Basically we can say both are sos formats and it is up to the user to use file extension `.sosnb` for scripts that are only working in interactive mode. Interface wise, we can provide options to do minor adjustment between the two, namely

```
sos convert interactive.sosnb --sos batch.sos --remove-cell
```

**Comment by gaow** [comment]
I'm not sure what's the best way to use SoS ... I tend to write batch.sos only to run them in batch mode (bioinformatics style), and interactive.sosnb exclusively for exploratory analysis (statistics style), so I do not foresee myself using this type of conversion a lot.

**Comment by BoPeng** [comment]
Do you use spyder (with `.sosnb`) or jupyter (with `.ipynb`) for interactive use? I think we can de-emphasize `.sosnb` and introduce spyder as a way to debug `.sos` script.

**Comment by gaow** [comment]
I use Jupyter, I guess mostly because I still prefer it over RStudio (and I take spyder an RStudio equivalent). Jupyter can give you WYSIWYG report, Rstudio needs `knitr`, but spyder will not give any report in HTML (displaying large tables nicely). So I am still on Jupyter.

**Comment by BoPeng** [comment]
Spyder also gives preview of tables etc because it uses the same kernel as Jupyter... The inspector feature is especially useful because it displays all the variables and their values (similar to Rstudio). Spyder also allows me to organize scripts more clearly.

I would say both Jupyter and Spyder have their pros and cons and I now like Spyder better than Jupyter unless I need to keep results for presentation or later reference.
