### ISSUE TITLE
Multiple `check_R_library` commands does not work in the same step

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#169]
For example:
```
[1]
check_R_library('stephens999/ashr')
check_R_library('rstudio/bookdown')
```
Will only install the first package not the 2nd. However breaking them into different steps will work.

**Comment by BoPeng** [comment]
I do not know why this happens but I suspect it is related to the complex logic with the current run function. I will have a look at this after I finish the work in the output branch.

**Comment by BoPeng** [comment]
Not sure what was the reason but I cannot reproduce the problem now.

**Comment by gaow** [comment]
I confirm it is resolved.
