### ISSUE TITLE
Resource control

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#17]
Limiting or monitoring the RAM and CPU (cores) the step uses?

**Comment by gaow** [comment]
Additionally snakemake allows for customized profile commands. Not sure how interested it is to have a user provided profiler for certain step if desired, and how we introduce it.

**Comment by bpeng2000** [comment]
I personally do not see a need for this right now so we will investigate this when a good application scenario comes out.

**Comment by BoPeng** [comment]
With https://github.com/BoPeng/SOS/commit/ada19fbb251d65287f41bd0487ddf01099ced174, sos is able to monitor the resources used by scripts. It is also easy to check the check the resource used by the main process, but it is not implemented yet.

Right now there is an `env.logger.info` after each script. We should figure out an interface for when and how to display such runtime information. `sos analyze` seems to be the way to go.

**Comment by gaow** [comment]
This is great! Are you suggesting storing them in some run-time database as we have proposed before? I recall we have discussed better ways to manage run-time signatures but we did not finalize it. Sorry for being off-grid for a while due to all sorts of craziness. I guess I should really start working on DAG because it seems I'm dragging it and you did not bring it up or step in just because you are graceful :)

**Comment by gaow** [comment]
So this new features gives me:

```
INFO: Completed in 5.1 seconds with 1 children and 0.00 % peak CPU and 90.1 Mb peak memory usage
```

I'm not sure why there is 0.00% peak CPU. I would expect something like 800% CPU as what in fact has happened. I was in fact running C++ codes swigged to Python where inside C++ the parallazation is implemented by OpenMP. Not sure if that's causing the problem.

**Comment by BoPeng** [comment]
I have to check that because I had only tested this for `sleep`. :-) The code should get hold of all children process so openmp should also be caught. Will look at this tonight.

**Comment by BoPeng** [comment]
This is fixed.

**Comment by gaow** [comment]
Cool: 

```
INFO: Completed in 5.1 seconds with 1 children and 795.8% peak (636.4% avg) CPU and 93.8 Mb peak (91.6 Mb avg) memory usage
```

**Comment by BoPeng** [comment]
Replaced with more specific problems/questions.
