### ISSUE TITLE
Use string interpolation with sos_run 

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#170]
Currently this script will result in syntax error:

```
[default_1]
input: '../library-interface/interface.sos'
sos_run('eqtlbma + default', source = [${input!ra}])
```
In principle I should not need to define an input file because `sos_run` should be executed anyways and `interface.sos` will take care of run signature. I do it this way because `source` in `sos_run` does not accept relative path (which should be easy fix), then I find it does not work either.

**Comment by BoPeng** [comment]
I do not understand why source does not accept relative path, please check `utils.locate_script` and see how it fails (print `filename`, `start` and `getcwd()`).

**Comment by BoPeng** [comment]
```
sos_run('eqtlbma + default', source = [${input!ra}])
```

is wrong because you are not using `${}` in a string. You should do 

```
sos_run('eqtlbma + default', source = ['${input!ra}'])
```

or

```
sos_run('eqtlbma + default', source = [os.path....(input[0])])
```

**Comment by gaow** [comment]
Ah my bad. that was dumb. I think we need `abspath`:

```
@@ -792,7 +792,7 @@ def get_output(cmd, show_command=False, prompt='$ '):
 #
 def locate_script(filename, start=''):
     #
-    attemp = os.path.expanduser(filename)
+    attemp = os.path.abspath(os.path.expanduser(filename))
```
Which works for me. Should I commit? It is annoying we have to do this all the time.

**Comment by BoPeng** [comment]
Yes, thanks.
