### ISSUE TITLE
configuration set conflict with python keywords

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#171]
For example, this will not work
```
sos config --set a 'all'
```
Because `all` is a python keyword.

```
yaml.representer.RepresenterError: cannot represent an object: <built-in function all>
```

**Comment by BoPeng** [comment]
The problem here is that `all` is treated as a valid python object (a function), and yaml cannot save it. The correct way to set it would be

```
sos config --set a '"all"'
```

Anyway, I have submitted a patch to handle python objects that cannot be saved in yaml format as string. This should be able to fix the problem.
