### ISSUE TITLE
Step parameters 

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#174]
There are advantages of defining local parameters.

1. The workflow would be easier to read if the parameters are defined when they are used.
2. Right now the parameters sections are shared across workflows defined in the same script so it can be confusing which parameter is for which workflow.
3. Local parameters allows us to encapsulate steps better. For example, in the future if we have a GUI, we can have steps with their own parameters.

The syntax could be something like:

```
[10]
parameters:
# comment 1
name1=default1
# comment 2
name2=default2
input:  

```

or

```
[10]
# comment 1
name1=default1
# comment 2
name2=default2

parameters: name1, name2
input:  

```

or

```
[10]
parameters: name1=default1, name2=default2,
    name3=default3

input:  

```

A potential problem with local parameter is how to handle

```
[10]
a=10

[20]
parameters: a=20
```

but I guess we can disallow parameters and parameters with the same name in the same workflow.

Of course we can keep global parameters section for global parameters (e.g. selection of workflows).

**Comment by gaow** [comment]
What is the difference between just defining variables in steps without tagging them as `parameters`? Mutability and accessibility from other steps? Sorry I always think local parameters are just variables you define right after the step names `[ xxx ]`. Not sure exactly what the difference is here.

**Comment by BoPeng** [comment]
The difference is that `name` will have value `value` instead of `default` for

```
[10]
parameters:  name=default
```

and `sos run workflow --name=value`.

**Comment by BoPeng** [comment]
If we do not really need comments to parameters, we can dismiss the dedicated `parameters` section and just define them in the global sections, something like

```
#!/usr/bin/env sos-runner

a = 1
b = 2
parameter: c = 3
parameter: d = 4

[10]
parameter: e = 5
input: 
```

**Comment by gaow** [comment]
Ahh I see. Right, this syntax above is a lot more consistent.

**Comment by BoPeng** [comment]
I also like the last syntax. SoS could be clever enough ti take comment before definitions as parameter comment.

**Comment by BoPeng** [comment]
This has been implemented and pushed to master. The implementation is actually easier than the previous one because we had to handle parameters ection for nested workflow etc and now we only need to handle `parameter: name=defvalue` as a regular expression.
