### ISSUE TITLE
Removal of special report syntax.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#175]
There are three ways to generate report,

```
report('''
this is report''')
```

```
report:
this is report
```

and

```
! this is report
```

Perhaps we should limit the number of syntax sugar and remove the special `!` syntax?

**Comment by gaow** [comment]
I use `report` in my notebook all the time because I think `!` look ugly ... so I have no object to drop it :)

**Comment by BoPeng** [comment]
Ok, let us remove `!` to keep sos simple.
