### ISSUE TITLE
Iterator through a table

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#176]
I am not sure there is a general solution but I have found a need to iterate through a table to perform some actions, something like

```
A  B   C
10  1  2
20  0.5 0.6
```

with script involving `A`, `B`, and `C`. I suppose direct input of `csv` file is not a good idea because there can be datatype and other issues, but we should be able to iterate through for example a pandas data frame.

```
table = pd.read_csv('data.csv')
input:  for_each=table???
run:
    script with ${_A} ${_B) and ${_C}
```

**Comment by gaow** [comment]
I keep separate utility functions -- loading data from file and parse -- and use that to set the input names.

But your `table` approach is very similar to `ngseasy` config where all parameters are kept CSV format. So this is definitely a common scenario people run into.

**Comment by BoPeng** [comment]
I suppose we can extend the `for_each='var'` syntax. If `var` is a pandas data frame, we can iterator through its rows, using row name (header) as temporary variables, perhaps with the `_` prefix.

**Comment by BoPeng** [comment]
Done with pandas dataframe support.
