### ISSUE TITLE
Logger handler not properly cleaned up

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#182]
I am using `env.logger` from `utils.py` and notice that logger handler is not properly cleaned up, for the codes below:

```python
from pysos.utils import env
env.logger.info('Have good night!')
env.logfile = 'test.log'
for i in [2,2]:
    env.verbosity = i
env.logger.info('Have good night to file!')
```

The output duplicates:
```
INFO: Have good night to file!
INFO: Have good night to file!
```
I printed out the handlers and I noticed they are not properly purged. The length of handlers is not zero after `removeHandler()` calls. So I apply the patch below:

```diff
diff --git a/pysos/utils.py b/pysos/utils.py
index 3cd32a2..a60d1a3 100644
--- a/pysos/utils.py
+++ b/pysos/utils.py
@@ -379,8 +379,7 @@ class RuntimeEnvironments(object):
         # logging from multiple processes.
         self._logger = logging.getLogger()
         # clear previous handler
-        for handler in self._logger.handlers:
-            self._logger.removeHandler(handler)
+        self._logger.handlers = []
         self._logger.setLevel(logging.DEBUG)
         # output to standard output
         cout = logging.StreamHandler()
```
and fixed the problem.

I'm wondering why `removeHandler` does not do the job. Also is there any problem to just reset handlers to `[]` instead removing them (should I commit the patch)?

**Comment by BoPeng** [comment]
As far as I remember, I used `self._logger.handlers = []` before and changed to proper `removeHandler` after I notice some problem related to multiple instance of handlers in multi-processing cases... Perhaps we should call `handler.close()` before removing them?

**Comment by BoPeng** [comment]
I see the problem.

```
        for handler in self._logger.handlers:
            self._logger.removeHandler(handler)
```
removes a handler and invalidates the iterator. I will submit a patch.

**Comment by gaow** [comment]
Working now!
