### ISSUE TITLE
SoS hang for having taking many jobs

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#183]
I have this script:

```
[default: sigil = "%( )"]
Nsamp = [5, 10, 20]
ncontrol = [100, 1000]
nullpi = [0.5, 0.75, 0.9, 0.95, 1]
seed = [x for x in range(100)]
input: for_each = ['Nsamp', 'ncontrol', 'nullpi', 'seed']
output: expand_pattern('Nsamp_%(_Nsamp)_ncontrol_%(_ncontrol)_nullpi_%(_nullpi)_seed_%(_seed)')
run:
echo output::%(input!,)::%(output!,) > /dev/null
```

The script hangs, after a few seconds of execution (nothing shows on `top`). But if you change the `seed` line to `range(10)` it works almost immediately. It seems to be an issue with multiprocessing module ...

However, if I debug the original script

```
sos run 1.sos -d -j8
```

It seems to work without an issue.

**Comment by BoPeng** [comment]
It appears that the result (which contains 300 filenames) is very large and choked `queue.put` although I doubt this would actually be the case.

**Comment by BoPeng** [comment]
should be fixed.

**Comment by gaow** [comment]
Confirmed!
