### ISSUE TITLE
Passing vars to Python kernel?

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#185]
Right now SoS will process `${ }` before it passes cell text to the underlying third-party kernel such as R or Python. I am wondering if it makes sense to pass the SoS variables to these kernels. It can be difficult to do it for R and other kernels, but passing vars to the Python kernel should be easy. We can either do this automatically, using options

```
%use python withvars
```
or explicitly specify the vars to be passed,

```
%use python vars=proj_dir
```

or

```
%vars proj_dir
```

which is equivalent to something like

```
%use python
proj_dir = eval(${proj_dir !r})
```

One consideration is that if we cannot do this consistently for all kernels, we should perhaps not do it. Another consideration is that we might not need the Python kernel at all if SoS kernel is compatible with it (e.g. with interactive mode, with all the additional magic).

**Comment by gaow** [comment]
> One consideration is that if we cannot do this consistently for all kernels, we should perhaps not do it.

I agree ...

**Comment by BoPeng** [comment]
But I hate to use

```
samples = eval("${repr(samples)}")
groups = eval("${repr(groups)}")
```

to pass variables and and it is so tempting to do

```
In[1] a=1
In[2] %use python
In[3] a
Out[3]: 1
```

The patch is actually very simple although we should consider the possibility that the recipient kernel is python 2, not python 3.

```diff
diff --git a/pysos/kernel.py b/pysos/kernel.py
index 90c52a1..4440206 100644
--- a/pysos/kernel.py
+++ b/pysos/kernel.py
@@ -31,6 +31,7 @@ import subprocess
 import zipfile
 import tarfile
 import gzip
+import pickle

 from .utils import env, WorkflowDict, short_repr, pretty_size, dehtml
 from ._version import __sos_version__, __version__
@@ -535,6 +536,11 @@ class SoS_Kernel(Kernel):
             if code.startswith('%with'):
                 self.original_kernel = self.kernel
             self.switch_kernel(options)
+            if options.strip() == 'python':
+                # if it is a python kernel, pass the SoS variables to it
+                sos_data = pickle.dumps(env.sos_dict.clone_pickleable())
+                code = "import pickle\nglobals().update(pickle.loads({!r}))".format(sos_data)
+                self.KC.execute(code, silent=True, store_history=False)
             lines = code.split('\n')
             code = '\n'.join(lines[1:])
             command_line = self.options
```

Perhaps we can add it as a hidden feature?

**Comment by BoPeng** [comment]
I just submitted a patch that uses syntax

```
%use python var1 var2
```
or

```
%with python var1 var2 ...
```

to pass `var1`, `var2`, etc to the python subkernel. I will not document this and we can remove it later if there are better ways to achieve this but right now I need `matplotlib` in python kernel and need to pass SoS variables to `python` kernel.

**Comment by BoPeng** [comment]
Re-implemented with a dedicated `%pass` magic, something like:

```
a=1
b=2
%use python
%pass b
b
```

At least this looks less ugly.

**Comment by gaow** [comment]
Great! At least we have something to use for Python now.

**Comment by BoPeng** [comment]
The rpy2 version might not be too difficult ... My concern is that how to properly convert objects. rpy2's method is to wrap R object with a Python layer (http://rpy.sourceforge.net/rpy2/doc-2.1/html/robjects_convert.html), but I tend to think we should do a complete conversion of simple objects, if most things we would like to convert are string <-> string and R vectors <-> python list.

**Comment by gaow** [comment]
Just a note here: R has `NULL`, `NA` and `NaN` types. We may have NULL -> None, NaN -> numpy.nan but no counter part for `NA`. Also there is such a thing called `factor` in R ...

**Comment by BoPeng** [comment]
So there cannot be an perfect conversion. The idea is to convert as good as we can and just tell users we cannot convert other types. If 99% of the cases we are just passing filenames and simple values, we should be fine.

**Comment by BoPeng** [comment]
For example, with a patch that I just submitted, we have

```
a = [1, 'ddd']
%use R
%get a
# a <- c(1, 'ddd')
# is executed
a
# ['1', 'ddd']
```

Perhaps we should use R list for python list, and R vector for numpy vector ... but the point is that we try to convert python object to native R object for practical use of SoS.

**Comment by BoPeng** [comment]
This method does not for large arrays because we essentially create an expression that will be passed as plain text and will be evaluated in the subkernel. However, there is a limit of the size of expression or jupyter buffer (reason unknown yet) so some information can be lost in this process...
