### ISSUE TITLE
Rstudio notebook

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#186]
Not sure if Jupyter or Spyder is the currently recommended SoS interactive UI. But Rstudio now has its own notebook:

http://rmarkdown.rstudio.com/r_notebooks.html

So it seems there must be people like myself who prefer a notebook style over integrated consoles.

**Comment by BoPeng** [comment]
Good feature. We cannot afford to create our own engine and have to rely on jupyter kernel though.
