### ISSUE TITLE
Syntax error for scripts with unquoted variable.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#187]
For example,

```
filename = 'file.txt'
R:
open(${filename!r})
```
would not work because `open(${filename!r})` is not a valid R syntax. We will have to use

```
filename = 'file.txt'
R:
open('${filename}')
```
but this would fail if `filename` contains `'`. Similarly, in interactive mode, if we would like to pass an arbitrary python variable to a Python subkernel, we cannot do

```
%use python
var = ${var!r}
```

and have to do something like

```
%use python
var = eval('${var!r}')
```

but the latter would fail if the representation of `var` contains `'` (e.g. `var={'a': 1}`). 

The solution seems to

1. For batch use, check syntax error after string interpolation but that would defer syntax checking from `inspection` state to `run` state because only then can we make sure `var` are valid SoS variables. 
2, For interactive use, because we are going to replace `inspection` + `prepare` + `run` with a single `interactive` mode, it seems ok to ignore the check syntax step.

**Comment by BoPeng** [comment]
I would propose that we stop syntax checking because it slows down inspect/prepare mode significantly, and because it does not work well in the cases mentioned.

**Comment by gaow** [comment]
I'm cool with stop syntax checking now that we save problematic scripts and point users to it. I personally find myself running `sos run -r` a lot these days to skip it!

**Comment by BoPeng** [comment]
OK. Will remove syntax checking code.
