### ISSUE TITLE
Portability of runtime signatures

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#19]
Runtime signatures are usually not portable because filenames and pathes would change when the project
is moved to another location. However, because it is possible for a project to be archived, and restored
for some further analysis, saving the runtime signatures with the project might be usable. In addition,
if runtime signatures include standard and error output of the commands, it can be useful to keep them
for later reference. The interface can be

```bash
sos admin --pack_runtime runtime.db
```

for packing runtime information to a file,

```bash
sos admin --unpack_runtime runtime.db
```

for unpacking runtime information of the current project, and

```bash
sos admin --unpack_runtime runtime.db
```

The `sos view` or `sos edit` commands might be used to show standard and error output of commands.

**Comment by gaow** [comment]
I have more thoughts on `runtime.db` than portability: we can also search (or `sos view`) it, for example, all steps that have changed `xxx.bam`. This DB therefore will have two purposes: portability and house-keeping. 

Will parameters be documented in this separatedly? For example, in simulations if we have:
```
for i in ...; do
  for j in ...; do
     simulate $i $j
  done
done
```

then if the parameters in runtime signature is separate, we can even query the database for given parameters. Not sure how useful it is but I suppose the implmementation is up to the design of signature format.

**Comment by bpeng2000** [comment]
Right now the signature only keeps hash value of commands and md5 of input/output/depends files. We can of course keep more information if needed.

**Comment by BoPeng** [comment]
The portability problem might be solved in another way around. That is to say,

1. Users move the project without signature (or remove existing signature).
2. We run sos in a special mode where signature files are reconstructed if the output file exists. This is the opposite of the `-f` options, and I have no idea how to name it now (perhaps `-F`).
3. If a certain step needs to be rerun, remove the output and re-run in regular mode.

This option can also useful during the development of SoS when the format of signature files are changed back and force...

**Comment by BoPeng** [comment]
Implemented in the [signature](https://github.com/BoPeng/SOS/tree/signature) branch (https://github.com/BoPeng/SOS/commit/9688fc34d0e2e66a7cac7dc7b6b4f4324f03d93c), temporarily with a `-F` flag.

**Comment by gaow** [comment]
It sounds like a viable solution and I cannot think of a better name than `-F`  for now.

**Comment by BoPeng** [comment]
The `-F` feature has proven to be very useful recently because I need to run parts of the workflow on the cluster and I had to rsync files back and forth and use `-F` on both sides.
