### ISSUE TITLE
String interpolation issue

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#194]
Here is the MWE:

```
[1]
dat = ["1.txt", "2.txt"]
python:
  print(${dat!r})
```

I expect to get `1.txt 2.txt` but I get `1.txt2.txt` (no space). If I add a comma in the print, e.g.
```
[1]
dat = ["1.txt", "2.txt"]
python:
  print(${dat!r,})
```
I get  `1.txt 2.txt` with space, not comma. This is because internally I get `print("1.txt", "2.txt")`. The behavior of comma is no longer string `join` in this version.

**Comment by BoPeng** [comment]
This makes perfect sense because `print('1.txt' '2.txt')` is equivalent to `print('1.txt2.txt')` and `print('1.txt', '2.txt')` is equivalent to `print('1.txt', '2.txt', sep=' ')`.

**Comment by BoPeng** [comment]
This also related to issue #187 because `print(${data})` is not a valid python expression before interpolation.

**Comment by gaow** [comment]
I see. I was trying to get "1.txt 2.txt" ... I guess  I can use `'${dat}'` instead.
