### ISSUE TITLE
Quick inspection / execution

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#195]
For a MWE:

```
[1]
a = [x for x in range(100)]
b = [x for x in range(100)]
c = [x for x in range(100)]
input: for_each = ['a', 'b', 'c']
output: expand_pattern('{_a}_{_b}_{_c}.test')
run:
  touch ${_output}
```

Inspection step of this script takes 10 minutes, compared to using itertools to combine these parameters and write the output which takes a few seconds. I'm in a situation where quick execution is crucial because I'm only interested in the transcript that SoS generates. But in general, there can be scenarios where one just want to quickly execute the script with as little overhead as possible (knowing the risk of course). Does this sound reasonable use case and is there a way to make it faster?

**Comment by BoPeng** [comment]
I am doing profiling the workflow and checking where it gets slow.

**Comment by gaow** [comment]
A related point from email threads earlier: we should disable transcribe in run mode

https://github.com/BoPeng/SOS/blob/master/pysos/actions.py#L417

However taking the transcript is not the speed bottleneck of the test script above.

**Comment by BoPeng** [comment]
Agreed. I am buried in post-leave stuff but will address this issue as soon as I can.

**Comment by BoPeng** [comment]
The bottleneck seems to be with evaluating the "output: " expression in the SoS namespace, which involves string interpolation. I cannot yet see a way to significantly improve the performance here. Still investigating.

**Comment by gaow** [comment]
Thanks for the thorough investigation! In this case (of manually writing the loop), I assume ordering of what's in the `for` part will matter. Does the code `['{_a}_{_b}_{_c}.test' for _a in a for _b in b for _c in c]` produce the same outcome as `interpolate('${_a}_${_b}_${_c}.test')` in terms of the ordering?

Also I'm wondering if there are other tricks can be used at the SoS script level to further speed it up. For example tricks to skip checks, file signatures, etc. My user case here can be simplified to just "touch" output files for once and there is no need to prepare, inspect or save anything for it; but the problem is that I have to touch nearly a million of this via SoS.

**Comment by BoPeng** [comment]
`expand_pattern('${a}_${b}_${c}.test')` is `['{_a}_{_b}_{_c}.test' for _a, _b, _c in zip(a, b, c)]`, and this is why I did not use `expand_pattern`.

For your application, I would say 1M small files can be disastrous for most file systems and you would better think of better ways to achieve what you need.

**Comment by gaow** [comment]
> ... takes 12.8 s, and replacing the last line with ... takes 4.19s. 

I can confirm this 3 time difference. I was also able to involve `input` in the loop and get it work with input files. The speed gain with `sos inspect` is 35 times -- this will certainly help! I agree 1M files is a bit out of the line but let's test the limit of SoS that way. 'll keep testing and share thoughts here.

**Comment by gaow** [comment]
It is more relevant to ask here about problem with keeping transcripts vs. generating transcript-like file manually. It is less efficient when transcripts are involved. For example I can get transcript for this workflow:
```
[1: alias = 'test']
a = [i for i in range(5)]
b = [i for i in range(5,10)]
output: '1.out'
for _a in a:
  for _b in b:
    python("print(${_a}, ${_b})")
```
However, the last line involves `interpolate()` which is very slow, compared to this one:

```
[1: alias = 'test']
a = [i for i in range(5)]
b = [i for i in range(5,10)]
output: '1.out'
for _a in a:
  for _b in b:
    print('{}_{}'.format(_a, _b))
```
The problem with the 2nd solution is that I have to use `sos run` instead which will look for `1.out` down the line that I cannot provide.

**Comment by gaow** [comment]
Not so fast: there is a problem with manually writing those loops, though: that will indeed accelerate the string evaluation process (thus inspection) but when it comes to running the pipeline, I am no longer able to do it multi-thread, with the `for` loop like in here:

```
output: ['{_a}_{_b}_{_c}.test' for _a in a for _b in b for _c in c]
for o in output:
    sh('touch ${a}')
```

How can this be resolved? If we fall back to using the string interpolation (the old slow code), is it possible to evaluate it in parallel? Currently it is computing using only one thread. I believe the most straightforward interpolation is to go parallel, if possible.

**Comment by BoPeng** [comment]
I already mentioned this. The very reason for having `for_each` in `input` is to allow parallel execution. Because sos does not know python for loop, it cannot execute the code in parallel.

Because the execution time is spread out in different parts of SoS, I do not see a bottleneck that we can magically improve the performance once resolved. You can also improve the performance slightly by using

```
output: '{}_{}_{}.test'.format(_a, _b, _c)
```

instead of 

```
output: '${_a}_${_b}_${_c}.test'
```

but such cases would be among the first few cases to be optimized soon.

**Comment by gaow** [comment]
In fact I use `output: out_file[_index]`.  The issue is having too many files -- but that sounds reasonable for a simulation pipeline. Here is an example
[test.tar.gz](https://github.com/BoPeng/SOS/files/450086/test.tar.gz). If you run `sos run -r test.sos.txt -c test.conf` you'll see what's going on. I was wondering if it is possible to use multiple threads to perform string interoplation inside SoS.

**Comment by BoPeng** [comment]
String interpolation can be improved (there are many ways), but it takes only 20% of execution time (because of `output` needs to be `eval`ed...  I will take your test case and see how far we can optimize it.

**Comment by gaow** [comment]
Thanks! Sorry I will have to improve this test case, though. In this version I removed all the R scripts leaving only `print(${output})` which in fact executes fast: in a few minutes, because it dies not have to interoplate other parameters. I'll redo the test case to reproduce what I deal with but not having to include lengthy R codes.

**Comment by gaow** [comment]
Update: when I made up the example I actually used less replicates. Looking back into my real case, which is 100 times the scale of this test, I realize that even if we can optimize the interpolation by much, I should perhaps re-design my procedure, because even if it passes the current stage of interpolation I'll end up having too many files. It is very easy to abuse SoS in such a way that people keep adding loops in `for_each` which results in exponential increase in files downstream. Since my test case does not contain things like `output: '${_a}_${_b}_${_c}.test'` it is perhaps not the best benchmark. 

What do you mean by "but such cases would be among the first few cases to be optimized soon." -- will this be optimized?

**Comment by BoPeng** [comment]
Just pushed a patch that optimize interpolation of simple cases (namely `${var}`). This case does not involve nested interpolation and does not have complex format string, and can use a simpler algorithm. On my machine, for 100000 string interpolation

.format: 2.28s (no interpolation)
old implementation: 12s
optimized implementation: 6s

**Comment by BoPeng** [comment]
The case is ${var} , which I have just optimized.

**Comment by gaow** [comment]
This is very good because that simple case is very often used!
