### ISSUE TITLE
Large intermediate files removal and skip rerun

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#196]
I recall we had the feature in VPT that we can remove large intermediate files and ask VPT to ignore those files by updating the signatures, so that those steps will not be executed again even after the files are removed. Is this feature ported to SoS?

**Comment by BoPeng** [comment]
Not yet. It was implemented as an action RemoveIntermediateFiles. Perhaps
there are better ways.

PS. I am back.

**Comment by BoPeng** [comment]
By better implementation I meant something like "sos cleanup", which could remove all untracked intermediate files (according to DAG) and replace large tracked files (with an option) with their signatures. This can be simpler and be applicable to all workflows, but with the downside being workflows cannot manage large intermediate files during execution.

**Comment by gaow** [comment]
A crude workaround though is to remove those files manually, `touch` empty files under the same name, and use `-F` in execution.

**Comment by BoPeng** [comment]
Name for the action? `remove(one_or_more_files, keep_signature=True)`?

**Comment by gaow** [comment]
`remove` sounds good to me. Would it be useful if we have some size limit in this action, e.g., remove when exceeding certain gegabytes?

**Comment by BoPeng** [comment]
Or something like `shrink`? This sounds better because `os.remove` is readily usable. The size logic can be useful but does not seem to worth a dedicated option. I suppose users can do something like `find ... -size -exec vat cleanup --shrink {} \;`

**Comment by gaow** [comment]
To clarify, we are talking about 2 independent options: 

1. Have an action similar to `RemoveIntermediateFiles` in VPT which, when used in a step, will swap specified files and keep a signature
2. Have a command `cleanup` that removes via commandline the files specified (and keep signature)?

Of course both will depend on DAG. For example, when, as an action, `RemoveIntermediateFiles(output, keep_signature=True)` will do nothing if there are still downstream procedures are yet to be performed. It will only delete when all file signature exist along paths it is involved in DAG. Same for the `cleanup` option.

Then what does the `--shrink` switch mean here? `shrink` could mean reducing size not by removing, but by "thinning" everything. `delete` maybe a candidate if we want to distinguish from `os.remove`

**Comment by BoPeng** [comment]
I just think `os.remove` (even `shutil.rmtree`) is enough for removing files and directories so there is no need to assign an action for such purposes. `shrink` (or something like that) is more appropriate for the task we would like to achieve. Because there is no such operation elsewhere, users can become curious and learn what this action does.

**Comment by BoPeng** [comment]
An `shrink` action has been implemented and (roughly) tested. Of course the name is not very appropriate and can be changed.

**Comment by BoPeng** [comment]
What if we save info of all files in dag so that users can remove actual files without affecting reexecution ?

**Comment by BoPeng** [comment]
Another side effect is that the overhead of saving and checking signature would increase significantly, which would be disastrous for applications with large number of intermediate and output files. Note that we always save signatures even with option `-F`.

**Comment by gaow** [comment]
Well, the large number of file situation is related to #195. The toy example I gave there creates many files, but in fact I only want to use SoS to build execution sequences (taking advantage of its syntax) without actually generating those files. It is impossible now because the next step always perform various checks on the expected input. 

In this issue, these checks might be performed on intermediate files.

Is there a way to  

```
[1: alias = 'test']
a = [i for i in range(5)]
b = [i for i in range(5,10)]
output: '1.out'
for _a in a:
  for _b in b:
    print('{}_{}'.format(_a, _b))

[2]
input: test.output, group_by=1
for i in input:
  print(i)
```
will quit with error `: 1.out not exist`. However if we can add something to `input` of step `[2]` saying it should skip any checks then the workflow will run. Or is there another way to achieve this? Either way, I'm saying may be able to bypass checks via special options and it may be useful for a mock pipeline like my case, or when there is large number of intermediate files that we do not really want to care.

**Comment by BoPeng** [comment]
Are you trying to get a transcript of commands to execute?

**Comment by gaow** [comment]
Yes essentially that's the case and the `inspect` mode may achieve it. However there are 2 caveats. First, transcript only works if I use actions `python`, `run` etc, not running a script like this, which will not generate a usable transcript. Also I can replace `print` with something to store data in a more compact way, not just a plain text. So in general it's like a mock SoS run here. The reason SoS is used instead of a plain Python script is because it can figuring out step dependencies on the fly, particularly when we have DAG implementation.

**Comment by BoPeng** [comment]
Let us discuss the transcript feature in a separate thread (perhaps you can create it with a real example) but keep this thread for removing intermediate files. How do you like the idea of keeping all file signatures? I like the idea because it does not require any particular input from users. They can remove files freely either in workflow or from command line.

**Comment by gaow** [comment]
Yes it does sound more convenient than having an action for it. However we have always been relying on deleting files to trigger re-execution. The concept seems very intuitive. Can we balance it by achieving this "free remove" via dedicated `sos clean` command so that files removed via this command are intentional and will not trigger rerun, while files moved by other means will still trigger rerun?

**Comment by BoPeng** [comment]
There are two options:

1. save file info by default and provide special command to trigger re-evaluation. One possibility is to add a target option to sos (sos -t path/to/file) which will remove the signature of this file and trigger re-evaluation. Another option is `sos cleanup file` which removes file (if available) and its signature.

2. do not save file info by default and provide commands and actions to save file info. We have the `shrink` action for now. A `sos cleanup file` command can be used to replace a file with its signature.

**Comment by gaow** [comment]
Option 1 sounds more intuitive. Not sure what the cost it is to save all file info when there are so many files. But if they are done during actual execution (not inspection or prepare) the users would not notice it. However if a user forgot to remove via `sos` but with a regular `rm` command, we then should make sure our `sos` command can additionally remove it's signature (sounds already is the case).

With this mechanism we can rediscuss the possibility to pack all the signature to transfer to another machine #125. Now the resulting pack will be more lightweight.

**Comment by BoPeng** [comment]
I also prefer option 1. The problem with signature is that we currently check signature also in inspection and preparation mode because it is likely that output files are generated not in an action (but in regular python code). Checking signature only in run mode would run the non-action multiple times. The catch here is that we also require such actions to complete in 5 seconds in inspection mode ...

As for an interface, we could have

`sos invalidate file`

or

`sos remove file`

followed by

`sos run workflow`

An option for `sos run` to combine the two commands also make sense but we are out of good option name.

**Comment by BoPeng** [comment]
Note that with a proper DAG implementation, we can probably skip signature check if a step is already checked in a previous stage.

**Comment by gaow** [comment]
For a combined command, `sos run -t` for "trash", `-d` for "discard", or `-r` for "remove and rerun"? 

Indeed it could be a lot of work to also check signature in preparation and inspection. The run command will hang on the terminal. 

Currently it is not possible to run without prepare/inspect. Do you think we should have a "go" mode that skips prepare/inspect? e.g. `sos run -g`? Then for very large files people can do prepare/inspect separately, or opt to skip it.

**Comment by BoPeng** [comment]
`sos remove` plus `sos run -r` looks good.

I am not very worried about signature performance because, although we cannot use sqlite database for sharing issues, we can optimize it later with for example a dedicated key/pair server.

Let us wait till the completion of DAG and see if the problem can be resolved, because as I have said we can ignore many steps with proper DAG implementation.

**Comment by BoPeng** [comment]
Another option, just for reference now, is to use

`sos discard` plus `sos run -d` for removal of files.

`sos run -i` inspects
`sos run -p` prepares
`sos run -r` runs
`sos run` is equivalent to `-ipr`
`sos inspect` equals `sos run -i`
`sos prepare` equals `sos run -ip`

**Comment by gaow** [comment]
I think it's good to have `discard` plus `-d` for file removal and `sos run -r` for executing without -p or -i.

**Comment by BoPeng** [comment]
These are implemented, pending more testing.

**Comment by gaow** [comment]
Perhaps we need to re-open this issue. I'm having 2 problems here. First, when for some steps an output file is generated yet is problematic, I noticed SoS will skip the step when I run it again. For example:

```
[1]
output: "test.pdf"
R:
pdf(${output!r}) # an empty pdf file is generated
some_bad_codes_that_failed_on_error()
dev.off()
```
then next time I'll have to `sos run test.sos -d test.pdf` otherwise it will not work. Another issue is that if I modify the codes in a step SoS will refuse to rerun if the output file exists. For example:

```
[1]
output: 'test.txt'
run:
  touch ${output}
  echo "changeme"
```
Run this code once, then change "changeme" to anything else, I'd expect it reruns and I see something echoed to the screen. However I don't.

**Comment by BoPeng** [comment]
For the first issue, if something wrong happens and R returns non-zero, the signature should not be generated.

The second issue should be a bug and I will look into it.

**Comment by gaow** [comment]
Will if you run the first piece of test code above, twice, this is the output:

```
[GW] sos run test.sos 

INFO: Executing default_1: 
INFO: input:   ['test.pdf']
Error: could not find function "some_bad_codes_that_failed_on_error"
Execution halted
INFO: 
ERROR: Failed to process statement R(r'''pdf(${output!r}) # an em...off()''')\n: Failed to execute script. The script is saved to /home/gaow/tmp/.sos/default_1_0.R. Please use command "Rscript --default-packages=datasets,methods,utils,stats,grDevices,graphics  /home/gaow/tmp/.sos/default_1_0.R" under /home/gaow/tmp to test it.

[GW] sos run test.sos 

WARNING: No MD5 signature for /home/gaow/tmp/test.pdf
WARNING: No MD5 signature for /home/gaow/tmp/test.pdf
INFO: Executing default_1: 
INFO: input:   ['test.pdf']
INFO: output:   ['test.pdf']
```

So clearly
