### ISSUE TITLE
Duplicated execution (and transcript)

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#200]
The MWE:

```
[a_1: alias = "first"]
a = [i for i in range(2)]
output: ['{}.txt'.format(x) for x in a]
for x, y in zip(a, output):
    run('echo {}; touch {}'.format(x, y))

[a_2: alias = 'second']
input: first.output, group_by = 1 
output: ['{}.txt'.format(x) for x in input]
print(input)
print(output)
for x, y in zip(input, output):
    run('echo {}; touch {}'.format(x, y))

[default]
sos_run('a_1+a_2')
```

When I run `sos inspect test.sos` I end up having this transcript:

```
/bin/bash:
    echo 0; touch 0.txt
/bin/bash:
    echo 1; touch 1.txt
/bin/bash:
    echo 0.txt; touch 0.txt.txt
/bin/bash:
    echo 1.txt; touch 1.txt.txt
/bin/bash:
    echo 0.txt; touch 0.txt.txt
/bin/bash:
    echo 1.txt; touch 1.txt.txt
```
Apparently the 2nd step is executed twice which is not right. If I do `sos run test.sos` I also see duplicated runs.

**Comment by gaow** [comment]
Also if I use `sos run -r test.sos` I'd get an error message:

```
Failed to process input statement first.output, group_by = 1 
: 0.txt not exist
```

**Comment by BoPeng** [comment]
In your second step, you loop through two input files, but `input` and `output` has two files so you are repeating the same thing twice, unless you do


```
output: '${_input}.txt'
for x, y in zip(_input, _output):
```

I need to run and will check the second problem later.

**Comment by gaow** [comment]
I do not get the above argument. I indeed have `input` and `output` both a list of 2 elements. At the 2nd step, the `input` is `['0.txt', '1.txt']` and `output` is `['0.txt.txt', '1.txt.txt']`. So when I do 

```
x, y in zip(input, output):
   ...
```
I should not get the same thing twice. In fact if I add `print` statement at 2nd step before the loop, I too get duplicated output, i.e., `input` and `output`  are printed twice. Perhaps I'm missing something obvious?

**Comment by BoPeng** [comment]
I meant, you are executing 

```
x, y in zip(input, output)
```

twice for `_input=['0.txt']`, and `_input=['1.txt']`, with identical `input` and `output`.

If even if you are confused with the `for_each` stuff, it might make sense to remove it, which will make sos step much simpler to understand (no more underscore variables). The only thing we are missing are script-format actions inside for loop and concurrent execution of looped actions.

**Comment by gaow** [comment]
Ahh sure ... I did not mean to have `group_by=1`. To achieve what I need I'd have to remove that. I think the logic is fine. Usually with `group_by` we'd then use in SoS actions the underscore variables. This script was modified from a version with underscore (as an attempt to replace string interoplations with manual loops) and somehow `group_by` skipped my eyes ...

Still the 2nd problem sticks: `sos run -r` would not work. Again:

```
[a_1: alias = "first"]
a = [i for i in range(2)]
output: ['{}.txt'.format(x) for x in a]
for x, y in zip(a, output):
    run('echo {}; touch {}'.format(x, y))

[a_2: alias = 'second']
input: first.output
output: ['{}.txt'.format(x) for x in input] 
for x, y in zip(input, output):
    run('echo {}; touch {}'.format(x, y))

[default]
sos_run('a_1+a_2')

```

**Comment by BoPeng** [comment]
The problem here is that the signature of `0.txt` exists so the first step is ignored, then the second step cannot proceed without `0.txt`. The solution would be a DAG that differentiate between real file exists and file signature exists. You can remove `.sos` to confirm this.

**Comment by BoPeng** [comment]
Or you can use `-f` for now to ignore signature.

**Comment by gaow** [comment]
Right, I confirmed it. However I thought with the current version it should not trigger rerun if signature files exists!

**Comment by BoPeng** [comment]
Note that VPT uses a trace-back method to address the problem (previous step skipped because of existence of file signature and later step needs real file), which is pretty troublesome. A DAG is definitely a better solution.

**Comment by BoPeng** [comment]
The DAG will be improved to handle this case.
