### ISSUE TITLE
Configuration does not load for nested workflow

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#201]
Here is MWE:

```
[test_1]
output: CONFIG["1"] + '.txt'
run:
  touch ${output}

[default_1]
sos_run('test_1')
```

with a configuration file `cfg.json`:
```
{"1": "test"}
```

Now if I run `sos run test.sos test -c cfg.json` it works fine. However, if I run `sos run test.sos -c cfg.json`, it would say:

```
ERROR: SoS workflow contains errors: test
[sos_run ('test_1')] RuntimeError:
	Failed to process step output: CONFIG["1"] + '.txt' ('NoneType' object is not iterable)
```
and `sos run test.sos default -r -c cfg.json`:

```
ERROR: Failed to process statement "sos_run('test_1')": Failed to process step output: CONFIG["1"] + '.txt' ('1')
```
It looks like for nested workflow the configuration file is not loaded. Not sure if its a bug or my stupidity.

**Comment by BoPeng** [comment]
Should be fixed now.
