### ISSUE TITLE
Problem with __max_jobs__ option 

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#202]
It looks like that `-j` is not behaving properly. Here is a MWE:

```
[1]
check_command('stress')
a = [i for i in range(20)]
input: for_each=['a']
output: expand_pattern('{_a}.txt')
task: concurrent=True
run:
  stress --cpu 1 --timeout 60
  touch ${_output}
```
And I only want 2 cpu threads:

`sos run test.sos -j2 -f`

At least on my computer with `top` I see a dozen process created, not 2. It seems fine with `-j1` though.

**Comment by BoPeng** [comment]
I did not pay attention to this parameter during code reshuffling because the current implementation works at the step level and it should works at the DAG level. I can correct it if it is an easy fix, otherwise let us wait for DAG.

**Comment by BoPeng** [comment]
Yes, it is an easy fix.
