### ISSUE TITLE
Require indentation for script format of actions?

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#203]
The script format looks good but has one big disadvantage, namely it is difficult to determine when it ends. For example, I cannot add a `function()` after the `sh` block in the following code

```
[10]
sh:
do_something

function()
```

because everything would be passed to `sh`. This has also caused problems for scripts with `[]` and `input:` and for syntax highlighting because the parser has to look for `[]` and `input:` etc to terminate the script block.

Other workflow tools address this problem by triple quotes but I think it is good enough to require indentation for scripts. That is to say, only `do_something` will be passed to `sh` and `function()` will be treated as a separate action in the following example:

```
[10]
sh:
  do_something

function()
```

**Comment by gaow** [comment]
I understand such needs, but same as one most common critic about Python, I can see chaos when `\t` is mixed with spaces, or when people mess it up because they forgot to indent some lines, etc, etc. It also makes it less straightforward to copy codes from existing R / Python scripts to SoS. 

We do have the triple quote sytax style. Can we use that if we want to mix codes like this:

```
bash('''
do_something
''')
function()
```

**Comment by BoPeng** [comment]
Indenting a block of code should be easy with any good editor.

In addition to problems with 

1. code with `[]` and `label:` starting at the first column
2. syntax highlighter difficulty
3. Cannot be followed by regular function but can be followed by another action

I had a problem with 

```
[10]
sh:
script

# a large block of to-be handled draft workflow
```

In this case the comment is also considered to be part of `sh`, and the script could not run because there are invalid `${ }` inside the comments. So you can see in this case there is no good way to really comment out that block of comment so that it is not processed by sos.

**Comment by BoPeng** [comment]
Oh, the comments can be ignored with something like

```
[10]
sh:
script

[comment]
# a large block of to-be handled draft workflow
```

but it is not an easy trick.

**Comment by gaow** [comment]
Right, I agree with all these problems. I also agree triple quote like `R(''' do sth ''')` will not work if we have to specify something like `R: workdir = ...`. I cannot think of a better way than indentation. Having a pair of `{}` is ugly. I'm only concerned of potential chaos: how will you detect an indentation? What if people use a mixture of tab and white space? In Python it does not matter as long as it is consistent, but other languages, say Make or YAML, are strict.

**Comment by BoPeng** [comment]
`textwrap.dedent` will keep empty lines (with space and/or tab), and remove common leading spaces (space and tab are different), so mixing tab and space might not be a big problem. Big separators like

```
'''
CODE
'''
```

or

```
{
CODE
}
```

are all ugly with large piece of code so only indentation makes sense here.

I do like the freedom to insert code as it is though.

**Comment by BoPeng** [comment]
There is a possibility of first-line indent, namely the first line determines indentation level, so we can allow

```
sh:
line1
line2
func() in sh
```

```
sh:
    line1
    line2
    func() in sh
```

and
```
sh:
    line1

func() outside of sh
```

This gives flexibility and backward compatibility but can be confusing from time to time.

**Comment by gaow** [comment]
This sounds a good idea! Another way is to define some keywords, such as 

```
sh:
line1
line2
END
func() outside of sh
```
though we should think of a good choice of that keyword. But I do think first-line indent is a fine idea.

**Comment by BoPeng** [comment]
`END` or anything else would not work because script can have anything. First-line indentation would be a bit difficult to implement but perhaps not that difficult.

**Comment by BoPeng** [comment]
Done. Documented at https://github.com/BoPeng/SOS/wiki/Documentation#script-style-function
