### ISSUE TITLE
Parameter defined in global section.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#204]
Right now 

```
parameter: name = default
```
is handled for name to read values from command line. It would be processed multiple times if such a line is in the global section but the overhead is acceptable.

The problem comes with the case when we would like to assign values to `name` programatically. For example,

```
parameter: par = 1

[work_1]
something(par)
[work_2]

[batch]
par = 2
sos_run(work)
par = 3
sos_run(work)
```

The current implementation assigns `par` to 1 when each step of `work` is executed (because it is in global section), but it makes more sense to keep value of `par`.

It is therefore unclear how `parameter:` should work in this case.

**Comment by gaow** [comment]
The point to have `parameter:` is to make it possible to change it in workflows. We would expect the behavior consistent between a regular workflow and a nested workflow. Hopefully technically it is not hard to assign `par` in nested flows.

**Comment by BoPeng** [comment]
There is also a problem with required parameter. It makes sense to define it in global section as follows 

```
parameter: par = int

[work_1]
something(par)
[work_2]

[batch]
par = 2
sos_run(work)
par = 3
sos_run(work)
```

for a regular workflow `work`, but it is actually not required in workflow `batch`.

**Comment by BoPeng** [comment]
There is yet another problem in that we current assume variables set in global section to be constant, so changing value of `par` later on (as in `batch` workflow) would trigger a warning.

**Comment by BoPeng** [comment]
For the first problem, we can take a `assign once` approach. Namely the parameter would be set once when the global section is read, but not any more if the global section is processed multiple times (due to nested workflow etc). We can exclude parameters from read-only list so that change their values would not trigger such warnings.

**Comment by gaow** [comment]
I did not notice the "warning" on this. I always have assumed that with keyword `parameter:` we can always change it from command line or from other workflows. Without `parameter`, whatever assigned in global section are constants thus read-only. 

However, if I do

```
parameter: par = int

[work_1]
par = int2
something(par)
[work_2]
something(par)
```
Should I expect in `work_2` the value of `par` is still `int` not `int2`? Same question holds for `batch`. Should we make these changes local or global?

**Comment by BoPeng** [comment]
Right now `work_1` has its own namespace so change of `par` is local. However `par` is marked as readonly because it is defined in global section so a warning should be given if another value is assigned.

The reason for readonly is that `global` section is executed multiple times before the execution of each step (because a workflow can have steps from multiple files) so changing these variables is not safe.

**Comment by BoPeng** [comment]
This is implemented in https://github.com/BoPeng/SOS/commit/ff2712e0fef646ede9a683f86b8d654b3b091516  and documented at https://github.com/BoPeng/SOS/wiki/3.-File-Structure#redefinition-of-parameter .
