### ISSUE TITLE
Non-file output and dependent files.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#205]
This is an extension to ticket #88

SoS steps can often depend on resources that are not pure files. There can be many examples but

1. docker image. A step depends on a local image that can be built or downloaded. 
2. executable. A workflow depends on an executable that can be installed on the fly, although exact where the executable is installed does not really matter (because the installation process would set up $PATH).
3. milestone. A target just saying something has been completed.

I would propose a `type:name` scheme for such files and allow SoS to treat them as dependency files. For example,

```
[10]
depends: 'executable:fastqc'
sh:
    fastqc 

[install_fastqc: provides = 'executable:fastqc']
sh:
    wget fastqc
    install fastqc
```

With the upcoming makefile-style rule, sos would check dependency for an executable called fastqc. If the executable file does not exist (in this case in `$PATH`), it would call the `install_fastqc` step and install it. Similarly, `docker:something` in the following example would be a target

```
[10]
depends:    'docker:something'
run:   docker_image='something'
   run something

[build_something: provides='docker:something']
docker_build:
    Docker file
```

SoS would check `docker images`, tries to download it, and/or build from the make-file rule.

For the milestone case, we could have

```
[10]
output: 'milestone:done'

[100]
depends: 'milestone:done'
```
so that step 100 can only be executed after step 10 is completed, although step 10 does not produce any output.

As we can see, the type of such target determines how they should be handled. We should ideally implement them as objects with `exists` interface so that can be incorporated seamlessly in the DAG framework.

**Comment by gaow** [comment]
So there are two parts in this problem:

1. Extend dependency logic to other types in addition to files
2. Use Make-style rule to handle this

For 2, we have discussed the "auxiliary step" design, which I believe is what `provides` does here.

**Comment by BoPeng** [comment]
For 2, yes, this is the simpler case for `auxiliary step` with no pattern etc. I think we agreed on `target` option but `provides` reads better.

**Comment by BoPeng** [comment]
Syntax wise, `docker('name')` and `milestone('string')` might be better and allows user-extended targets (e.g. derive something from a pysos class).

**Comment by BoPeng** [comment]
Similarly, `input: dynamic('*.fastq')` might be better than `input: '*.fastq', dynamic=True`. Not a big deal though.

**Comment by gaow** [comment]
I agree the `()` syntax is more natural. Having `:` after `:` is awkward. An additional parameter might also do, for example `depends: something, target_type=docker`, or even `input: '*.fastq', target_type=dynamic`

**Comment by BoPeng** [comment]
It is natural to have a unified `Target` class and `milestone`, `executable`, `dynamic` etc would create objects of its subclasses with different behaviors. For example, `ExecutableTarget.exists()` would check if a command exists, and `MilestoneTarget.exists()` would check a special signature. The DAG would be simpler to implement with such a class.

**Comment by BoPeng** [comment]
Just to add that a directory can also be a target, although something like `directory('path', non_empty=True)` would make it more useful to detect if something has been created.

**Comment by BoPeng** [comment]
This is partly implemented ... with the implementation of non-file target `executable`. New types of targets, if needed, will be discussed in separate threads.
