### ISSUE TITLE
Inspection cannot properly skip comments

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#208]
MWE:

```
[1]
R:
print("Happy Labor day!")

# [2]
# day = "Sept 5, 2016"
# R:
# print("Happy ${day}")
```
with `sos run test.sos` I get:

```
ERROR: SoS workflow contains errors: default
[R (interpolate(r'''print("Happy Labor da] NameError:
	name 'day' is not defined

```

**Comment by BoPeng** [comment]
This is a duplication of #163 and also discussed in #203 . The problem is that comments here are considered part of the R script and are interpolated. The solution is to indent script in section 1.
