### ISSUE TITLE
Design of auxiliary step

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#209]
Proposed syntax

```
[stepname: provides=pattern]
input:
```
where `pattern` can be a patten of filename or one or more targets. For example

```
[index_bam: provides='{bamfile}.bam.idx']
input: '${bamfile}.bam'
output: '${bamfile}.bam.idx'
sh:
       index bam file
```

or

```
[build_fastq: provides=executable('fastq')]
sh:
   build fastq
```

Auxiliary steps are processed as

1. When some target is required, SoS would look for all auxiliary steps and check if one of them can provide the target.
2. If no step or multiple steps are found, an error will be raised.
3. If `target` matches one of the patterns, the variable will be defined. E.g. if `sampleA.bam` matches `{bamfile}.bam`, `bamfile` is defined as `sampleA`. Otherwise nothing else is defined (e.g. for `executable` target.
4. The step will be processed as usual. The only difference is that the default input of the step (if `input` is not defined) is not the result of previous step, and should be defined, and should be usually defined using the variable defined from pattern.

I feel that this is the easiest implementation for make-file like rules. Please comment if it cannot cover some practical usages.

**Comment by gaow** [comment]
This sounds like make-style thus should be good for most applications. What if the auxiliary rules are defined in a separate file -- does the syntax to source such rules from another file require the `provide` syntax in the step that sources them?

**Comment by BoPeng** [comment]
This is a good question, we have `sos_run(nested_workflow, source=another_file)` but there is no way to formally include another file in the present file. Perhaps something like

```
include("another.sos")
```

is needed.

**Comment by gaow** [comment]
Yes I think so. I think it is reasonable that people may want to put auxiliary steps in separate files creating a utility-like script. Then with `include` we'll have to deal with conflicts (or overwrite) when there are identical steps.

**Comment by BoPeng** [comment]
Yes, reading the file is easy (we can handle `include` in the parser but handling conflicts can be troublesome, and there can be trouble with nested and duplicated includes.

**Comment by BoPeng** [comment]
We should perhaps set the default `${output}` as the matched target so that

```
output: '${bamfile}.bam.idx'
```
could be ignored from 

```
[index_bam: provides='{bamfile}.bam.idx']
input: '${bamfile}.bam'
output: '${bamfile}.bam.idx'
sh:
       index bam file
```

Of course users are free to produce more outputs using `output` keyword. After all, the steps are executed as usual after the initial variables are set.

**Comment by BoPeng** [comment]
Implemented in trunk.
