### ISSUE TITLE
Finer control of file signature / rerun within steps

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#210]
For starters, I have this script:

```
[1]
x = [1]
input: for_each = ['x']
output: expand_pattern('{_x}.txt')
run:
  echo ${_output}
  touch ${_output}
```
which will generated `1.txt`. When I update the first line of script to `x = [1,2]` and run it again, the entire step reruns. This is a bit annoying when for example I update the parameters (usually add more parameters) and only to find that all steps are executed again. Is there a way to be able to control at a finer scale so that file signatures are recognized / skipped at the command level, not the step level?

**Comment by BoPeng** [comment]
The problem here is that SoS does not know if `x` is used by `run`.

**Comment by BoPeng** [comment]
Duplicated ticket with #61

**Comment by BoPeng** [comment]
This is implemented with specific examples in `TestExecute.testLoopWiseSignature`
