### ISSUE TITLE
include action or directive.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#211]
There is a need to include external `.sos` files in a script. For example, a file with common auxiliary steps can be included. The included files should be considered in place so it is possible to do

```
include('file1.sos')

[10]
sos_run('workflow_in_file1')
```

and do

```
sos run script workflow_in_included_sos
``` 

Because the current code collects name of workflows during parsing, it is better to process `include` during parsing as if the content is in place in the script. Therefore, the common `action` syntax does not really work

```
include("dfadf")
```
because they are processed after parsing, and people tend to misuse it as

```
if something:
   include('one.sos')
else:
   include('two.sos')
```

and the content of the script cannot be really there (not within a code block).

We therefore might need some special syntax ... or we can add a fake python statement (similar to `import`). In the end, if possible, I would prefer something like

```
include script.sos
```

or even

```
from script.sos import step1, step2
```

We might also do

```
include script
```

if we enforce file extension `.sos`.

**Comment by gaow** [comment]
`from script.sos import step1, step2` sounds tempting. However does it matter if we cannot 100% reproduce the Python behavior, e.g, `from script.sos import step1 as step, step2 as another_step`. If this is hard or unnecessary we should then stick to `include`. I'm not sure if it worth it to only import specified step from script. `include` sounds good enough to me.

**Comment by BoPeng** [comment]
I have a feeling that sooner or later we will have a feature request for `from script include step1`, but it should be good enough to have `include script` for now.

**Comment by BoPeng** [comment]
We can also restrict `include` to be before anything else in the script, which could immensely simplify implementation because we do not have to parse all python-looking statements.

**Comment by gaow** [comment]
> We can also restrict include to be before anything else in the script

Sounds fair enough. Or we introduce some ugly prefix like `%include` (swig-style), or `%from script import step`, to distinguish well enough from Python statements. I actually think it might be good idea to be able to import steps up-front and abandon `sos_run(nested_workflow, source=another_file)`. In that case we can give a warning and refuse to import a step if there is a conflict, in which case one has to use `%from script import step as another_step` to rename it.

**Comment by BoPeng** [comment]
I agree that there is less a need for `source=another_file` with `include`, although `sos_run` is still needed for (dynamically) composed workflows.

**Comment by BoPeng** [comment]
Implemented.
