### ISSUE TITLE
Handling of global sections with include.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#212]
Things are getting complicated with the introduction of `include`. If we have conflicting definitions, e.g. 

`A.sos`

```
resource = 'path1'

[A]
use resource
```

and `B.sos`

```
resource = 'path2'
[B]
use resource
```

If we use both `A.sos` and `B.sos`, it becomes difficult to decide how to handle `resource`. Currently SoS is doing something complicated, namely treating the global sections as local definitions to their file. That is to say, with

```
sos('A+B', source=['A.sos', 'B.sos'])
```

step `A` from `A.sos` would use `path1` and step `B` from `B.sos` would use `path2`. 

The problems gets complicated with

C.sos
```
include A.sos, B.sos
sos_run('A+B')
```

because everything in `A.sos` and `B.sos` are included in C.sos and there is no way to avoid he conflict.

I am not sure what is the best way to handle global sections in these cases.

**Comment by BoPeng** [comment]
To make things less complicated, I think we should 

1. remove the source option for `sos_run` so that there is only one way to include other files.
2. allow `include script [as alias]`. All names included in this way, just like import, need to be referred to as `script.name` or `alias.name` if `alias` is defined. For example

```
incude fileA, fileB as BB
print(fileA.resource)
print(BB.resource)
sos_run('fileA.A + BB.B`)
```

3. allow `from script include *`. This basically includes everything in the current script. We should handle conflict and duplicate accordingly.

3. allow `from script include name [as alias]` to include part of the variable or workflow. The names would be accessed without script name.

4. We should continue to monitor change (conflict) of global variables. We can either reduce changing of readonly variable from error to warning, or allow the addition of a parameter to ignore the error.

A lot of work is needed to implement all these. :-(

**Comment by gaow** [comment]
`fileA.resource` solves the step name conflict issue. Is it possible to overwrite without warning global variables using values from the main script, when the global variable appears in both scripts? It makes intuitive sense to use the one from the main script not the sourced script so it would be great if the program does not make a fuss about it.

**Comment by BoPeng** [comment]
This is now implemented (pending testing and documentation). The readonly issue is more complicated (involves parameters) and will be discussed in other threads.
