### ISSUE TITLE
Re-design of report features

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#220]
The anonymous report feature has many problems:
1. It does not have an explicit target so it is difficult to use file signatures to control the re-generation of reports.
2. It is not possible to control the order of reports given the random execution nature of DAG executor.

It is therefore necessary to define explicit output and let users decide how to put pieces together.

**Comment by gaow** [comment]
A related issue to part 2 of this ticket is the progress bar in `-v1` mode that I find more friendly than `-v2` but is possibly broken by the nature of DAG. Hopefully the resolution is similar.
