### ISSUE TITLE
-r mode has to go.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#228]
As more and more features now depend on DAG prepared during preparation stage, the `-r` mode (sequential execution skipping preparation step) has to be removed. For example, we now depends on the preparation step to check which parameters a step has used so that it can create a signature from the values of these variables. This is something that has to be done during string interpolation and statement evaluation...

The performance of SoS has decreased a lot due to more thorough analysis of the steps (we have to tokenize the statements) but at least we now get the following working:

```
parameter: gvar = 10

[10]
# generate a file with parameter
output: 'myfile.txt'   
python:
    with open(${output!r}, 'w') as tmp:
        tmp.write('${gvar}')
```

with commands

```
sos run test --gvar 20
sos run test --gvar 30
```

Previously because the script does not change, step 10 will be ignored for the second run.

**Comment by BoPeng** [comment]
Implemented.

**Comment by gaow** [comment]
But it looks like `-r` option is still available from the command interface, and is still usable. I noticed with `-r` it does not throw DAG related information, though.

Performance-wise, removing `-r` brings back my simulation setting where there are so many parameters to evaluate that it takes long time to evaluate. But I guess either we live with it, or I'll change many of my string interpolations to manual loops as previously suggested #195

**Comment by BoPeng** [comment]
I do not see `-r` in the master branch here. Check #230 for performance.

**Comment by gaow** [comment]
Oops right `-r` is gone on master. Ok I'll hold back changing my code to manual loops and use it to test performance when evaluations are removed from `prepare` mode.

**Comment by BoPeng** [comment]
Thanks. The bottomline is that we (SoS) should optimize, not users.
