### ISSUE TITLE
Installation with dependencies

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#231]
Currently I have to manually install a few packages that I believe can be included in `setup.py`

```
diff --git a/setup.py b/setup.py
index 41d10f4..96c8352 100644
--- a/setup.py
+++ b/setup.py
@@ -182,9 +182,12 @@ setup(name = "sos",
           'networkx',
           'pydotplus',
           # for RQ task-execution engine
+          'arrow',
+          'Flask',
           'rq',
           'rq-dashboard',
           # for celery task-execution engine
+          'tornado == 4.2.0',
           'celery',
           'flower',
       ],
```
However I'm worried particularly for `'tornado == 4.2.0'`. On my computer it says `flower` only works for this version so I had to downgrade this package. This can cause issues.

A more general question is that is there a better way to distribute the package to be relatively independent of system packages thus cause less troubles in installation and maintenance? due to the nature of SoS I bet it is difficult.

**Comment by BoPeng** [comment]
For some reason I need to run setup.py twice to get rq installed, I suppose your patch could fix it? I do not see a big problem with flower dependency right now. Celery is included to compare to rq and I am almost certain now that we can remove celery when we reach beta since rq is good enough and easier to work with.

**Comment by gaow** [comment]
> For some reason I need to run setup.py twice to get rq installed, I suppose your patch could fix it?

This will do (install `rq-dashboard` first then `rq`). In fact if that sequence is adjusted then `arrow` and `Flask` can be automatically installed. I'll submit the patch. 

> we can remove celery when we reach beta

Great! We'll see at beta how difficult it is to pip install all the dependencies.
