### ISSUE TITLE
Variable target?

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#237]
Basically a step is executed when a variable is needed and not in namespace. The step serves the purpose of "serving" some information to other steps. Syntax wise, it is possible for us to use explicit target 

```
[flagstat: provides=variable('mapped_reads')]
input: '${samplename}.bam.flagstat'
with open(input[0]):
    mapped_reads = ...

[report]
depends: variable('mapped_reads')

print('Mapped reads are ${mapped_reads)')
```

or we can make things implicit, by 

```
[flagstat: shared='mapped_reads']
input: '${samplename}.bam.flagstat'
with open(input[0]):
    mapped_reads = ...

[report]

print('Mapped reads are ${mapped_reads)')
```

The latter is doable because we now have a list of variables used in a step. In this case `report` uses `mapped_reads` and `flagstat` produces `mapped_reads`, `flagstat` will be automatically executed before `report`.

**Comment by BoPeng** [comment]
Implemented in https://github.com/BoPeng/SOS/commit/3278018284915dce0bcd1bb21e32becded586ecd , I do not really like the syntax that much so this might be changed or removed later on. Right now this seems to be a good solution for my need.

An example of `sos_variable` target is

```
[A: shared='b']
b = 1

[C: alias='c']
k = 2

[all: shared='p']
depends:
    sos_variable('c'),
    sos_variable('b')

p = c.k + b
```

Note that here SoS automatically translates `shared='b'` to `shared='b', provides=sos_variable('b')`.

**Comment by gaow** [comment]
I haven't experienced a need for this feature myself but looks useful!

**Comment by BoPeng** [comment]
This is not needed in a forward style because we can just put the step providing information before the ones that need them. The make-style is more intuitive from time to time, and allows better reuse (define but not used).

In theory this can be achieved automatically, namely we should be able to figure out what variables are used in a step. However there are so many ways to define a variable and it is difficult to determine if a variable is defined locally and does not depend on external step. For example, in

```
[A: shared='a']
a = 1

[B]
from module import *
print(a)
```

`a` can be a local variable imported from another module so step `B` does not depend on `A`. Target `sos_variable('a')` forces this dependency.
