### ISSUE TITLE
Section option "name"

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#238]
Right now we have section names

```
[A_1]
[A_2]
[A_3]
```

but `A` does not mean anything in terminal and DAG output. It would be more informative to use

```
[A_1: name='prepare']
[A_2: name='align']
[A_3: name='call']
```

to that we can display progress as `A_3 (call)` ...

**Comment by gaow** [comment]
We have `alias`, though. Can we make use of that?

**Comment by gaow** [comment]
I see .. `alias` can be different from `name`, and I see the need to have `name` separately. For example two computational steps may have different names yet same alias `XX` because a third step may take input of `XX.output` and depending on context `XX` may come from either step.

**Comment by BoPeng** [comment]
Or we can do

```
[A_1 (prepare)]

[A_2 (align)]
```

**Comment by gaow** [comment]
This reads better!

**Comment by BoPeng** [comment]
OK, I will implement this, although the option name `alias` is not very intuitive, and can be removed if we have `shared`. I will create another ticket for it.

**Comment by BoPeng** [comment]
Implemented at https://github.com/BoPeng/SOS/commit/6ac89176d214db642d312563200193e89d9ca3ce
