### ISSUE TITLE
Better name for section option "alias"

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#239]
`alias` is used to expose local variables in a step to other steps and provides similar function to `shared`. The name is not very intuitive and we might be able to remove the option given the overlap of functionality.

**Comment by BoPeng** [comment]
Another quirk of this alias option is it is totally clear what the loop variables would be for cases like

```
[A_1: alias='b']
output: 'a.txt'

[A_2]
input: for_each='b.output'
```

We uses `_b` but in theory people can do 

```
input: for_each='b.input,b.output'
```

so `_b_input`, `_b_output` can be better. Using shared for this purpose is clearer but more troublesome,


```
[A_1: shared='b']
output: 'a.txt'
b=output

[A_2]

input: for_each='b'
```

**Comment by BoPeng** [comment]
Note that a potential way to simplify 

```
[A_1: shared='b']
output: 'a.txt'
b=output

[A_2]

input: for_each='b'
```

is 

```
[A_1: shared='b=output']
output: 'a.txt'

[A_2]

input: for_each='b'
```

which means we are creating an alias `b` for an expression `output` in step `A1`.

One slight advantage of `alias='b=output'` is that it is clear that `b` will be evaluated after the completion of the task. In an extremely case,

```
[A_1: alias='b']
input: 'a.txt', 'a2.txt'
output: '${_input}.processed'

b = output[-2]
```

would fail because `output` has only one element in the first `for_each` loop. Using

```
[A_1: alias='b=output[-2]']
```

avoids this problem.

**Comment by BoPeng** [comment]
Or if using a statement (`b=output`) in option is not pythonic, we can do something like

```
[A_1: shared={'b': 'output', 'c'='k'}]
```

**Comment by BoPeng** [comment]
I would propose that we merge `alias` and `shared` using the dictionary syntax.

**Comment by BoPeng** [comment]
The new syntax for option `alias` is implemented in https://github.com/BoPeng/SOS/commit/a4d6a5b09c089b10e8829da8920a1b3ebb6e0f62 

Basically, we can shared a single variable `c`

```
[a: shared='c']
c = 4
```

a list of variables

```
[a: shared=('c', 'd')]
c = 4 
d = 5
```

shared a variable with another name

```
[a: shared={'c': 'd'}]
d = 5
```

or gives an expression

```
[a: shared={'c': 'd+5'}]
d = 5
```

**Comment by BoPeng** [comment]
The new syntax for option `alias` is implemented in https://github.com/BoPeng/SOS/commit/a4d6a5b09c089b10e8829da8920a1b3ebb6e0f62 

Basically, we can shared a single variable `c`

```
[a: shared='c']
c = 4
```

a list of variables

```
[a: shared=('c', 'd')]
c = 4 
d = 5
```

shared a variable with another name

```
[a: shared={'c': 'd'}]
d = 5
```

or gives an expression

```
[a: shared={'c': 'd+5'}]
d = 5
```

**Comment by BoPeng** [comment]
Step option `alias` is removed  https://github.com/BoPeng/SOS/commit/8c5fcfaa15aaa114ba26bf801e67dbe56cb45399 because it overlaps with option `shared` in function.

**Comment by gaow** [comment]
So, to clarify we'll no longer have `alias` for steps. Previously SoS like:

```
[1: alias='test']
...

[2]
input: test.output
```

Will have to be written via sharing of variables, e.g., 

```
[1: shared='test_output']
...
test_output = step.output

[2]
input: test_output
```

Is this the case?

**Comment by BoPeng** [comment]
Yes, you can also write

```
[1: shared={'test_output':'output'}]
...


[2]
input: test_output
```

which is preferred because the assignment of `test_output` happens only after the step is completed, and it is possible to do

```
[1: shared={'test_output':'output[0]', 'test_outpu1': 'output[1]'}]
...


[2]
input: test_output
```

to shared filename instead of a list.

**Comment by gaow** [comment]
Nice. Let me edit the wiki along the way

**Comment by BoPeng** [comment]
Thanks, `shared` accepts

1. A string (variable name)
2. A sequence of string (variables)
3. A map between variable names and expressions (strings) that will be evaluated upon the completion of the step.

**Comment by gaow** [comment]
BTW there is this note in the wiki:

>NOTE: Because global variables are readonly, variables defined in shared option has to be parameters.

However it seems it's also Ok to not define the shared variable up front as `parameter: ...` which makes sense because the syntax is otherwise too troublesome. Can we change the wiki to:

> NOTE: Because global variables are readonly, variables defined in `shared` option cannot be global variables.

**Comment by BoPeng** [comment]
You are right, shared variables can be parameters or new variables, and cannot update existing global variables.

 I have updated the wiki.
