### ISSUE TITLE
Puzzling warning message

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#249]
I'm just wondering why there is "warning" message for commands / scripts that I run, for example 
![2016-10-10-20-33-17_scrot](https://cloud.githubusercontent.com/assets/917985/19256069/2c8730f8-8f29-11e6-9eaa-037ccfc7f6d0.png)

Makes me wonder if I'm doing anything wrong but it does not seem obvious.

**Comment by BoPeng** [comment]
Looks like uncleaned debugging message.

**Comment by BoPeng** [comment]
Ok, this is a message that is displayed if the action is not completed in 5 second, originally from the interactive mode. It is no longer needed in run mode because each step now has a progress counter showing how long the job has been running (start after 10 s).
