### ISSUE TITLE
Auxiliary step variable sharing problem

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#251]
Here is the MWE:

```
[work_1: shared = {'data': 'output_rds'}]
input: "1.txt", "2.txt", group_by = 'single', pattern = '{name}.{ext}'
output: expand_pattern('{_name}.out')
task: concurrent = True
run:
  touch ${_output}

output_rds = [x[:3] + 'rds' for x in output]

[default]
sos_run("work")
```

This example works with `sos run test.sos`, but not `sos run test.sos -j8`, which gives the following:

```
INFO: Executing default_0: 
INFO: Executing workflow work with input unspecified
INFO: Executing work_1: 
INFO: work_1 input:    ['1.txt', '2.txt']
INFO: work_1 output:   ['1.out', '2.out']
ERROR: Failed steps:
ERROR:     work_1: ''
WARNING: RuntimeError("Failed to evaluate shared variable data from expression output_rds: name 'output_rds' is not defined",)
ERROR: Failed steps:
ERROR:     default_0: ''
WARNING: RuntimeError('Failed to process statement \'sos_run("work")\\n\\n\': Workflow work is terminated prematurally with 1 failed and 0 pending steps',)
ERROR: Workflow default is terminated prematurally with 1 failed and 0 pending steps
```

**Comment by gaow** [comment]
Now with an update to the current master 5135635319cb8892d6de4b9910333307b60ae080, even the example without `-j8` refuses to work, the error message now is:
```
sos run test.sos 
INFO: Executing default_0: 
INFO: Executing workflow work with input unspecified
INFO: Executing work_1: 
INFO: input:    ['1.txt', '2.txt']
ERROR: Failed to process statement 'sos_run("work")\n': Failed to process step output: expand_pattern('{_name}.out') ('output_rds')
```
However if I add `-f` it will work. So to reproduce this issue with the current master, use `sos run test.sos -f` to see what works, and `sos run test.sos -f -j8` to see how it does not work.

**Comment by BoPeng** [comment]
Your example is not supposed to work because statement after `task` are executed in a separate process so `output_rds` is not accessible from the calling step. This is one of the reasons I put expressions for `shared` in the header.

**Comment by BoPeng** [comment]
Just submitted a patch to fix previous patch.

**Comment by gaow** [comment]
I see ... so will this work instead? `[work_1: shared = {'data': '[x[:3] + 'rds' for x in output]'}]`? I can test as soon as my current pipeline is done running.
`

**Comment by BoPeng** [comment]
Yes, but the trunk is a mess now. I dislike changes that breaks many tests but `prepare` has to be totally rewritten.

**Comment by gaow** [comment]
Right, I confirm the syntax works and will make it clear in the wiki that expression like this is supported. I see that `prepare` is being worked on along with `dryrun` modes. Please take your time. For the time being I'll only report issues that I believe independent of these changes.

**Comment by BoPeng** [comment]
We also need to warn users of this side effect of task, namely variables executed in tasks are not visible to the step.
