### ISSUE TITLE
Look for advice on dynamically evaluating shared variables

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#252]
This is more of a question not an issue. What I want to do simplifies to this:

```
parameter: A = []

[work: shared = {'A': 'output'}]
output: '1.txt', '2.txt'
run:
  touch ${output}

[another_work]
has_A = len(A)
input: '1.txt', '2.txt', group_by=1
python:
  if ${has_A}:
    print(${A[_index]!r})

[default]
sos_run('work+another_work')
```

So if I run the `default` workflow I'm all good. But there are times when I do not run the first part `work` but only run the other part `another_work`. Then index out of range error will show up at evaluation stage. 
```
ERROR: Failed to execute workflow another_work
[another_work_0] RuntimeError:
	Failed to process statement python(r'''print(${has_A})\nif ...r})\n\n''')\n: list index out of range: A[_index]: A[_index]!r
[another_work] RuntimeError:
	1 failed step: another_work_0
```

In practice I cannot use the `if` logic outside action `python` because the actual code is more complex. I wonder what one can do for situation like this. Thanks!

**Comment by gaow** [comment]
I should say that it should be possible to get around the problem by doing `[_index]` outside string interpolation, so in practice it might not be such a big deal, if the solution complicate things from the designing point of view.

**Comment by BoPeng** [comment]
The issue is with string interpolation of `    print(${A[_index]!r})` when `A` is empty, right? Will

```
stop_if(len(A) == 0)
python:
    ...
```

work? You can also do

```
    print(${A[_index] if A else None!r})
```

**Comment by gaow** [comment]
Yes it's the issue when A is empty. `stop_if` works for this example but not my actual case. The `    print(${A[_index] if A else None!r})` is great idea. Let me see if there is a place in the documentation we can put it in.

**Comment by gaow** [comment]
I see it's already there "If you are unhappy with the string conversion, you can always format your object using python expressions such as ${repr(obj)} and ${', '.join(x for x in obj)}." Guess it is time for me to refresh on these pages!
