### ISSUE TITLE
Merge -t (target) and -d (discard) options?

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#253]
Target means what we would like to generate, we do this by trim the DAG with only nodes related to specified targets. Discard means we would like to regenerate some targets, even if they already exist.  We can perhaps merge these two option because it is difficult to image `-d` intermediate results.

Also, the current implementation of these options are difficult to use in that users have to specify exact targets. It would be helpful to allow something like `sos run script -t *.html`.

**Comment by gaow** [comment]
Just a though: is it possible to allow for (re)generating by step name, i.e. `sos run script -t "[worker_2]"` and let SoS figure out the proper target to generate?

**Comment by BoPeng** [comment]
Yes, we need to decide on logics of these options. When we execute a workflow, we at least expect the final product to be available (e.g. output of the last step, with the exception that there is no output for that step). So it makes sense to re-run steps to generate the last result, even some unnecessary intermediate files have been removed.

Following this logic, we can say the default target is the output of the last step, and we can specify alternative targets to be generated. In case there is no regular step or workflow, auxiliary steps can be executed to produce these targets.

The 'step' target can be achieved from specifying subworkflow. For example

```
sos run work_-2
```

Output from `work_2` would be produced because this is the last step of the specified subworkflow. Here `-2` in `work_-2` means from start to step 2.

**Comment by gaow** [comment]
Can the same logic be extended to `sos clean`? I'm not sure how often one would clean up some workflow as if they have never been executed. I can possibly image when people run something, generate large files, dislike what they get but do not know a better solution. While working on fixing things up he/she might want to get rid of those bad outputs and extending `sos clean` to this might be useful.

Syntaxwise, I find `work_:2` and `work_2:` looks nicer on the screen, though.

**Comment by BoPeng** [comment]
Right now, my logic for `sos clean` is

1. run workflow, specify an output directory for each sample
2. after completion, I would like to remove all unnecessary files from the directories for archival purpose so I run

```
sos clean sample_1 sample_2 -f -d
```

**Comment by gaow** [comment]
So `sos clean sample_1 sample_2 ` will then only keep files and directories generated by steps `sample_1` and `sample_2`? Then this is like what I proposed, but complementary. I was essentially saying for example `sos clean sample_1 -f -d -c` (suppose we have `-c` for complementary, though wondering why we do not have `-c` for `config` here with the `clean command`) will perform clean up for all steps except `sample_1`, i.e., `sample_1` related files will be removed.

**Comment by BoPeng** [comment]
```
sos clean . -d
```

removes all folders that are not generated by any of the workflows.

There are two types of sos generated files, tracked and untracked. I remove untracked files to keep the tree clean, and you would like to remove tracked files, but what is the point of keeping untracked files in these folders?

Perhaps we can add an option `-t` for tracked files.

**Comment by BoPeng** [comment]
The `1:10` idea is taken and implemented.

**Comment by gaow** [comment]
Oh I was not suggesting keeping untracked files in these folders. I'm just saying it might help to have a way to systematically removing tracked (yet for some reason no longer wanted) files, just like the way we regenerate them.

**Comment by BoPeng** [comment]
Do you want to remove all tracked files, or some of them? If we are removing the "trunk" (sos tracked files), namely if we are not **cleaning** the trunk, the command should be called something other than `clean`.

**Comment by gaow** [comment]
I see, and I agree it is not "cleaning" trash, but rather cleaning bad tracked files ... yes it's removing some tracked files. Right now instead of removing files we regenerate them. I propose this because I often find myself in a situation where I do not like what I get yet do not have a fix right away, and I do not want to keep those bad files on my drive until I properly regenerate them.

**Comment by BoPeng** [comment]
Ok, let us clarify our usages here.

1. remove large intermediate files

  Just remove. SoS keeps file signatures so they can be removed without affecting later steps, unless they are needed to run a later step.

2. re-generate final result

  Do nothing. SoS will always generate the last result. It will re-generate removed intermediate files if needed. **This is not the current behavior.**

3. remove some tracked files

  Removal of files will not work because we also need to remove their signatures. `sos remove`?

4. cleanup the tree to keep only tracked files

  `sos clean -f -d`

**Comment by gaow** [comment]
Yes -- and we should add that we will merge `-d` and `-t`.

**Comment by BoPeng** [comment]
If you agree on these behaviors, we need syntax for 4.

**Comment by gaow** [comment]
Yes these behavior looks good to me. I take that you are referring to `sos remove`? We need to be able to remove via step name and via files. So positional arguments can be file names or step names, for example:

```
sos remove worker_1
```

Will remove files generated by worker_1;

```
sos remove *.pdf
```

will remove all tracked PDF files. We can possibly have `-c` option for complementary if it is straightforward enough to do, for example:

```
sos remove work_1 -c
```
will remove everything but work_1 generated files, and 

```
sos remove *.pdf -c
```
will remove tracked files that are not PDF.

**Comment by BoPeng** [comment]
Do we still have `clean`?

**Comment by gaow** [comment]
Sure, `clean` is useful removing irrelevant files. I'm thinking if it makes sense to have one command that does both `sos clean` and `sos remove` ... But I think having two commands is perhaps a better option, that makes our logic more clear.

**Comment by BoPeng** [comment]
I was also trying to merge the two, something like sos remove -u (untracked)

**Comment by gaow** [comment]
I am not sure now. There is pros and cons for both solutions. But if we use one command, shall we make `-u` a flag, like `-c` for complementary?

**Comment by BoPeng** [comment]
Let me try:

1. remove content and signatures of specified files and directories.

   ```
  sos remove dirs files
  ```

2. remove only tracked files from specified files and dirs (remove signature if files do not exist).

  ```
  sos remove -t dirs files
  # or
  sos remove dirs files -t
  ```

3. remove untracked files and directories from specified files and directories
  
  ```
  sos remove -u dirs files
  # or
  sos remove dirs files -u
  ```

4. Option `-n` for showing but not removing.

The 

```
sos remove -u dirs files
```

format allows

```
sos remove some -u untracked -t tracked
```

but it seems clearer to allow only one option in a command.

**Comment by BoPeng** [comment]
All behaviors are implemented, pending testing.
