### ISSUE TITLE
RQ/Celery fails for nested workflow

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#258]
The script in question (from one MWE for another ticket):
```
[work_1: shared = {'data': 'output'}]
input: "1.txt", "2.txt", group_by = 'single', pattern = '{name}.{ext}'
output: expand_pattern('{_name}.out')
task: concurrent = True
run:
  touch ${_output}

[work_2]
input: "1.txt", "2.txt", group_by = 'single', pattern = '{name}.{ext}', paired_with = ['data']
output: expand_pattern('{_name}.out2')
task: concurrent = True
run:
  touch ${_data} ${_output}

[default]
sos_run("work_1+work_2")
```

So if we run `sos run test.sos -j8 -f ` it works. But appending `-q rq` to it would not work. It simply skips the runs. However, if I explicitly run `sos run test.sos work` then `-q rq` will work.

**Comment by BoPeng** [comment]
We need a customized rq worker that can be terminated from sos, and can report jobs that have been processed.

**Comment by BoPeng** [comment]
This has been fixed.
