### ISSUE TITLE
_index issues with concurrent process

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#262]
I noticed this problem as I was digging into some unexpected results from my work. Here is the MWE:

```
parameter: A = []

[work: shared = {'A': 'output'}]
output: '1.txt', '2.txt'
run:
  touch ${output}

[another_work]
input: '1.txt', '2.txt', group_by='single'
task: concurrent=True
python:
 print(${_index})
 print(${A[_index] if A else None!r})


[default]
sos_run('work+another_work')
```

So with `task: concurrent=True` I get:

```
0
1.txt
0
1.txt
```
which is wrong. But removing that line, I get the correct result:
```
0
1.txt
1
2.txt
```
I did not expect `_index` behave this way. Am I missing something or it is a problem we should fix?

**Comment by BoPeng** [comment]
This is a bug ...

**Comment by BoPeng** [comment]
Fixed.

**Comment by gaow** [comment]
Nice patch :)
