### ISSUE TITLE
Passing matrices and dataframes between SoS (python) and ir kernel

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#265]
`%put` and `%get` currently works for simple datatypes. It is important to pass matrices and dataframes between SoS and ir kernels, perhaps through temporary `.csv` files.

**Comment by BoPeng** [comment]
https://github.com/wesm/feather

Looks like a great project to transfer data frames between Python and R.

**Comment by gaow** [comment]
I actually have looked into this before ... I wanted to pass between python dictionary and R list which is more general solution. That involves using rpy2 and store tempary RDS files. If you do not mind using rpy2, I can put my `read_rds` and `save_rds` codes into `utils.py` as a starting point. Basically with that one can save a python dictionary of whatever data type into RDS file as an R list, and vice versa.

**Comment by BoPeng** [comment]
I would much prefer a feather solution because I can have native data frame in both Python and R. The problem with `rpy2` is that the object passed from R is not native Python and can be difficult to handle.

**Comment by gaow** [comment]
feather deals with single data frame. We might get it work for matrix which is essentially data frame with less information. Same holds for vectors or single numbers (simple variables) though it would be a bit wasteful for these objects to be saved in one file. But what should we do if we want to communicate multiple objects, e.g. multiple matrices, or very often I find myself dumping to disk a dictionary of very different data type for one problem (e.g., parameters of different dimensions -- tensor, matrix or vectors -- from some inference procedure). That's why I did not dig into feather but rather started something that converts between python dict and R list via rpy2.

I'd be very much interested in finding a feather based solution!

**Comment by BoPeng** [comment]
The more complex the data structure is, the less likely we can find perfectly matched native data types in R and Python. Because `%get` and `%put` are very limited anyway, I do not mind enhancing its capacity gradually.

I just submitted a patch to do Python -> R transfer

```
import pandas as pd
import numpy as np
arr = np.random.randn(1000) 
arr[::10] = np.nan
df = pd.DataFrame({'column_{0}'.format(i): arr for i in range(10)})

%use R
%get df
dim(df)
```

Note that compiling feather-format from source is not easy on mac and it is much easier to use conda as suggested in [feather-format installation page](https://github.com/wesm/feather/tree/master/python).

**Comment by gaow** [comment]
Great! I see the patch :)

I agree that more complex data structure is likely to have perfect solution. But there is one fundamental question: is it possible to use single file to put together multiple objects? If it is not possible we might not want to bother trying more complex structure -- I'm specifically talking about Python dict <-> R list conversions. Many R program essentially returns a list of data frames and numbers, e.g. `lm()`. The point is that we mostly want to use R for heavy lifting statistics that may result in complex output (`lm()` is just trivial example) then use Python to take care of the rest. That's why I find R list conversion most useful.

**Comment by BoPeng** [comment]
My use case is mostly using python to prepare a data frame and use R to analysis it. The patch handles this but not the other direction (result back to Python) yet.

Note that the current implementation does not use file. It simply convert python/R object to expressions that are executed on the other side. That is to say

```
a <- '123'
```

is passed for python object `a = 123`. This works ok (and fast) for simple types (including sequence of the same type), and I am trying to make dataframe a 'simple' type using feather.

The R->Python transfer is more troublesome. It uses `dput` to write R object to some long expression and use Python to parse it. I have not been able to find a easier and more robust solution.

**Comment by BoPeng** [comment]
In terms of R->Python implementation, you should be looking at line 604 of kernel.py, 

```
 self.KC.execute('{}\ndputToString(list({}))'.format(dputToString_func, 
                ','.join('{0}={0}'.format(x) for x in items)),
                silent=False, store_history=False)
```

Here `dputToString_func` is a function defined at line 256

```
dputToString_func = '''
dputToString <- function (obj) {
  con <- textConnection(NULL,open="w")
  tryCatch({dput(obj,con);
           textConnectionValue(con)},
           finally=close(con))
}
'''
```

Then on the SoS side it gets an expression from message `execute_result` with a messy text like

```
    '[1] "structure(list(a = 1, b = \\"a\\"), .Names = c(\\"a\\", \\"b\\"))"'
```

The `from_R_expr` function parses this text and evaluate it (line 266). Since you are better at R, I hope that you can rewrite `dputToString` to get Python expression, such as

```
dict(a=1,
 b= "a",
 c= feather_read(".sos/feather_df_123.feature")
 d = dict(k = 5),
)
```

**Comment by gaow** [comment]
Indeed communication via string for simple types is very efficient. How about the middle ground, i.e., vectors and matrices? Also we might want to discuss down the line how we want to handle multi-dimensional array such as cubes or beyond ...

In fact we've done some string communication between Python and R before: 

https://github.com/vatlab/VariantTools/blob/master/variant_tools/rtester.py

The function `Str4R` on line 123 does the job. Back then we send data matrices of small genomic blocks (transcripts / genes) from python to R so we convert everything via string including large matrices. We can review those lines of codes (for Python 2 mostly) and adapt them for `dputToString` -- I can do that though it'd be a bit hard to test now (I do not even have Python installed on my macbook though I can try to run a jupyter server from my office computer and get connected)

**Comment by BoPeng** [comment]
For matrices, we might be able to use http://dirk.eddelbuettel.com/code/rcpp.cnpy.html to load numpy saved `.npy` file from R, although this can be an overkill for small and/or 1-D array.

**Comment by BoPeng** [comment]
`Str4R` is already achieved by `R_repr` in `kernel.py` although that function is a bit limited right now and we can enhance it with more data types, at least for `numpy.array` (1 and 2D).

The more troublesome part is R->Python conversion. The current implementation is very rough and we need a much better function. We also should run the conversion function once with `%use R` instead of passing it each time with `%put`.

**Comment by BoPeng** [comment]
R -> Python data transfer has been rewritten. https://github.com/BoPeng/SOS/commit/557f7e52f816e477195bc12e0db63e374c4de0e7  

The intended data type mapping is as follows, but I currently do not use `numpy.array` for numbers (lists are used). It should be easy to update the `..py.repr` function defined in `kernel.py` for this.

| R  |  length (n) |   Python |
| --- | --- |---|
| NULL | |    None |
| logical |  1 |  boolean |
| integer |  1 |  integer |
| numeric |  1 |  double |
| character |  1 |  unicode |
| logical |  n > 1 |  array |
| integer |  n > 1 |  array |
| numeric |  n > 1 |  list |
| character |  n > 1 |  list |
| list without names |  n > 0 |  list |
| list with names |  n > 0 |  dict |
| matrix |  n > 0 |  array |
| data.frame |  n > 0 |  DataFrame |

**Comment by BoPeng** [comment]
Done.
