### ISSUE TITLE
Replace check_R_library with target Rlibrary?

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#286]
A `Rlibrary` would make sense in a scenario like

```
depends: Rlibrary('ggplot2')
R:
   library(ggplot2)
   # plot
```

A hard decision to make is whether or not `Rlibrary` should try to install the library when it is not available.

**Comment by BoPeng** [comment]
Implemented in https://github.com/BoPeng/SOS/commit/5da34c2b2f3771c3aa1fc0666f215f6ef22c5a24  We will decide if we should remove `check_R_library`.

**Comment by gaow** [comment]
I have no objection to remove `check_R_library` -- this interface makes more sense and is more consistent with that of executables.

**Comment by BoPeng** [comment]
Following the same logic, I will also remove `check_command`.
