### ISSUE TITLE
nbviewer for our examples

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#287]
Not sure how to set it up, but we should be able to display our examples without having to fi open them in a jupyter server, as show at http://nbviewer.jupyter.org/github/mbakker7/exploratory_computing_with_python/blob/master/notebook1_basics_plotting/py_exploratory_comp_1_sol.ipynb

**Comment by BoPeng** [comment]
This is a service called nbviewer http://nbviewer.jupyter.org/

**Comment by jma7** [comment]
Is this what you want?
http://nbviewer.jupyter.org/github/BoPeng/SOS/blob/master/development/docker-notebook/examples/example.ipynb

**Comment by BoPeng** [comment]
Yes, the only missing part is the syntax highlighting is gone. I suppose this is because SoS uses its own codemirror syntax highlighter and the nbviewer does not understand. 

SoS uses its own codemirror highlighter defined in https://github.com/BoPeng/SOS/blob/master/sos/jupyter/sos_codemirror.js which is installed to jupyter kernel directory by `setup.py` (search `sos_codemirror.js`). I suppose the command line `.ipynb` to `.html` converter can make use of our highlighter, perhaps through an option.
