### ISSUE TITLE
Update release script to include steps to update amazon EC2 instance

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#303]
with latest version of sos and docker image.

**Comment by jma7** [comment]
A script is added to automate the update of docker and sos on ec2. A pem file is needed to put in the local folder to connect to ec2.

**Comment by BoPeng** [comment]
Great. I will create a pem file and try it later. Is the script already on ec2, or do we pass the latest version of the script on the fly? The latter seems to make more sense.

**Comment by jma7** [comment]
The script is at local in development folder.

**Comment by BoPeng** [comment]
done (https://github.com/BoPeng/SOS/commit/9710f96a00fa08b51734cf3a9abd35f076e0a9f8). The chown is needed because the docker server needs write permission to the directories.
