### ISSUE TITLE
Examples are not linked to SoS homepage.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#304]
release script converts them to html format with links to source code. e.g.

http://bopeng.github.io/SOS/doc/examples/update_toc.html

**Comment by BoPeng** [comment]
We can add them to `documentation.ipynb` easily after the workflow is setup.

**Comment by jma7** [comment]
So it will be a link on documentation page to update_toc.html?

**Comment by BoPeng** [comment]
yes. there should be a seprate section for examples and a list of such examples with brief descriptions.

**Comment by BoPeng** [comment]
Done.
