### ISSUE TITLE
Jupyter webpage theme

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#306]
The default Jupyter notebook theme is a bit dull. Here is a command line program that changes the default notebook theme on one's computer, and I assume consequently the resulting HTML theme

https://github.com/dunovank/jupyter-themes

We can further beautify docs #269 with a good theme. I find `grade3` nice looking

**Comment by BoPeng** [comment]
Some theme system allows switching theme from the pages themselves, does this one work that way, or do we have to choose one for the users?

**Comment by gaow** [comment]
Not sure about other theme systems -- this is the first theme system I've tried. Are there other good ones you are looking at? For this one, after installing the program, run, for example:

```
jt -t grade3 -T -N -f ubuntu -nfs 12 -tfs 12 -tf ptsans -nf ptsans
```

Then the notebook will change from

![2016-12-07-19-03-00_scrot](https://cloud.githubusercontent.com/assets/917985/20993478/180542e6-bcb0-11e6-930b-ad3f43e24a64.png)

to 

![2016-12-07-19-01-58_scrot](https://cloud.githubusercontent.com/assets/917985/20993481/1be62916-bcb0-11e6-8c4f-dee3bb0a052a.png)


which I think is an improvement

**Comment by BoPeng** [comment]
I meant if there is a dropdown box on the HTML file with themes to choose from. I used some PHP website and wiki systems and they have this kind of skin mechanism. This one does not seem to have it.

Another question is what is needed to be put the website to make the theme available there. I think you can try to run the converter (`release convert_documentation`) and see if there are additional files under `website/doc/documentation` and if the converted HTML file keeps the theme.

**Comment by gaow** [comment]
I see ... well this generates static HTML with improved themes, but there is no option for users to choose. Yes it does keep the theme in HTML, though for some reason it does not work for PT Sans on my computer. Here is what I currently find best looking:

```
jt -t grade3 -T -N -f ptmono -nfs 12 -tfs 12 -tf droidsans -nf droidsans
```

and running 

```
jupyter nbconvert --to html SoS_Kernel.ipynb
```

Gives this page:

![2016-12-07-19-16-22_scrot](https://cloud.githubusercontent.com/assets/917985/20993709/ac80bf76-bcb1-11e6-9759-1d05f5e91baa.png)

**Comment by BoPeng** [comment]
I agree that it looks much more polished. If you are going to push this, please add to `release` the package you installed (also the TOC stuff I did), and the command you run to get theme so that Jun and I can update our local jupyter theme.

**Comment by gaow** [comment]
Well, I'd like to do that, but I'm really having problem installing the TOC extension (as you can see my exported HTML does not have TOC) ... still trying to fix it. But in the mean time you can try it out: all I did was just 2 lines:

```
pip install jupyterthemes
jt -t grade3 -T -N -f ptmono -nfs 12 -tfs 12 -tf droidsans -nf droidsans
```

and then run `release` to update the HTML files. The side-effect is that it will change, once and for all, the look of all Jupyter notebook since, which maybe a good thing, but you can add to `release`:

```
jt -r
```
to restore to default.

**Comment by BoPeng** [comment]
I am also having trouble get toc2 working on my home computer after installing the theme. Maybe there is some conflict in the js code.

**Comment by gaow** [comment]
Hmm ... actually even before installing the theme I cannot get toc2 to work -- I never had toc2 work! But perhaps it is different cause yet same effect on your computer and mine.

**Comment by BoPeng** [comment]
I just installed the theme on my office machine and I can no longer view any document.

**Comment by gaow** [comment]
This is crazy ... I'm still trying to fix toc2 but I guess there is no point for this if you cannot get it work on your end.

**Comment by BoPeng** [comment]
Oh, my two step instruction lacks one step
```
jupyter contrib nbextension install --user
```

**Comment by BoPeng** [comment]
This doc is updated, with working TOC and theme.

http://bopeng.github.io/SOS/doc/documentation/SoS_Kernel.html

**Comment by jma7** [comment]
So you want every pages looks like this right? As you said, I found that some local hacking of toc2 js is needed to make this happen.

**Comment by BoPeng** [comment]
I did not do any local hacking. There might be some browser caching issue but everything works ok after refresh, clear cache etc on both my home and office computer.

As for which theme to use, I do like the new font. The layout and color are better than stock but there are problems (e.g. wider body than header, error not in red). Since it is so easy to adjust, I think we can just push the new pages and adjust the look later in consistent with the homepage.

**Comment by jma7** [comment]
I mean some hacking need to be done to set all the pages using side-bar instead of floating-bar and add a link to home page somehow. All those styling could be changed through custom css.

**Comment by BoPeng** [comment]
The TOC hacking could be done in `toc2.js`, where a toc file could be read (you can of course find another solution). I did not read the documentation carefully but I have the impression that the initial location (floating or side) could be configured from command line or configuration file).

**Comment by jma7** [comment]
Yes, there is a toc2.tpl file in the templates folder could be used to set default.

**Comment by BoPeng** [comment]
I am not sure which method works best, but I could imagine changing

```
sec1
sec2
sec3
```

to

```
HOME
doc1
doc2
cur_doc (doc3)
-> sec1
-> sec2
-> sec3
doc4
doc5
```

so that when a user select `doc2`, he could jump to `doc2` with TOC
```
HOME
doc1
doc2
-> sec1
-> sec2
doc3
doc4
doc5
```

This would not work for python's super long doc (which has previous-section, next-section etc) but could work for us.

**Comment by gaow** [comment]
I like this newly proposed method. However we might want to separate doc with tutorials. I can imaging after SoS is stabilized the doc will not change much but we might be constantly adding tutorials so it can potentially get quite long.

Regarding the new theme: there is also other styles / fonts one can choose from here:

https://github.com/dunovank/jupyter-themes

There is also parameter for line height and cell size. It is a matter of mix-match and find the best looking option (which is very subjective). 

Another option is to convert to only the core HTML:

```
jupyter nbconvert --to html --template basic
```
and add HTML header / css to the page generated. That gives us more flexibility, though I'm not sure how toc2 will be effected.

**Comment by BoPeng** [comment]
The theme you proposed has two problems:

1. as a working environment the header (menu) is narrower than cells. This is NOT a problem because there is no menu in the HTML output.
2. `stderr` (error) and `stdout` outputs are not differentiated, this is problematic. Is there an option for this?

![image](https://cloud.githubusercontent.com/assets/9889312/21017679/c9d6f0da-bd2f-11e6-9239-1d3140f7cfb3.png)

**Comment by gaow** [comment]
No I do not find there is the option ... however, I think we should perhaps use these themes as "template" to develop our own. I've figured out what we'd need by comparing HTML generated with / without the theme:

[theme.diff.txt](https://github.com/BoPeng/SOS/files/639980/theme.diff.txt)

I think it is good idea to save this to css file and hack into generated HTML pages to use this css.

**Comment by gaow** [comment]
Another options is to download the `jt` source code, modify these style sheets and install:

https://github.com/dunovank/jupyter-themes/tree/master/jupyterthemes/styles

We can fork this to your github account, make changes and we can all download from the forked version to install.

**Comment by BoPeng** [comment]
It is not that complicated, the class around error is 

```
<div class="output_subarea output_stream output_stderr output_text">
<pre>ls: Auxil*: No such file or directory
</pre>
```

so we only need to find the definition of `output_stderr` and change its background. You already have in your diff

```
+div.output-stderr {
+ background-color: #ebb5b7;
+}
```

and you will need to figure out which option sets this`#ebb5b7`.

**Comment by gaow** [comment]
Yes if we decide to hack into the code it is straightforward. There is no option that sets it. It uses templates (those *.less) files in:

https://github.com/dunovank/jupyter-themes/tree/master/jupyterthemes/styles

where the color is hand-coded. I think it is best idea that you (or @jma7 or I) fork this repo, make various changes to those *.less files and let others install `jt` via `pip install http://github.com/xxx` where `xxx` is URL to this forked / modified theme repo.

**Comment by jma7** [comment]
If there is not too much changes in the styling, we could just use the custom.css in the folder to make some customization.

**Comment by BoPeng** [comment]
I would say this belongs to final touch and should be done later. The one you proposed looks good enough to me so let us use it for now. After we have the homepage, toc, installation instruction etc all in pace, we can have a global css file to be used by **all pages** to have consistent look throughout the website.

Right now the priority should be on the content (jun on toc, gao on doc or website content...)

**Comment by jma7** [comment]
I just wonder what is the ordering of docs?

**Comment by BoPeng** [comment]
Random for now. I can make the changes later. I assume that you can have a toc file with lines like

```
<a href="Auxilary_Steps.html">Auxiliary steps</a>
```
or
```
Auxilary_Steps.html    Auxiliary steps
```

that we can adjust whenever we add or remove docs or tutorials.

**Comment by jma7** [comment]
http://bopeng.github.io/SOS/doc/documentation/Auxiliary_Steps.html

This need a custom template put into ```jupyter_contrib_nbextensions/templates/``` to happen.

**Comment by BoPeng** [comment]
You meant on the website or locally? It works well now as far as I can tell.

**Comment by jma7** [comment]
Need to put files in local ```jupyter_contrib_nbextensions``` folder.
