### ISSUE TITLE
website banner image

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#322]
For or banner, perhaps we should can something like 

![image](https://cloud.githubusercontent.com/assets/9889312/21157997/215187b6-c141-11e6-8a60-963118cb5444.png)

Basically with all the icons for all scripting languages we can find, put them together around an icon for SoS… 

SoS has a basic icon like 
![image](https://cloud.githubusercontent.com/assets/9889312/21158078/70db6ee6-c141-11e6-841e-36464b336a13.png), with svg source code in https://github.com/BoPeng/SOS/blob/master/sos/converter.py#L442

I am bad at art though...

**Comment by BoPeng** [comment]
![image](https://cloud.githubusercontent.com/assets/9889312/21167446/2a5a2738-c172-11e6-8ef1-5575b0bc96f8.png)

might work with the right font/color for SoS texts.

**Comment by jma7** [comment]
How about this one? 
Check https://unsplash.com/search/computer for more. 

![xekxe_vr0ec-markus-spiske](https://cloud.githubusercontent.com/assets/22623882/21170119/e83841f8-c187-11e6-9293-426399a342bf.jpg)

**Comment by BoPeng** [comment]
This one has too many colors, which makes it difficult to let the text (SoS) stand out. The goole app one (first picture) whitens the icons for this purpose and that is why I liked that one. However, getting all the icons in these kind of shape needs some PhotoShop work.

**Comment by BoPeng** [comment]
But the idea of morphed screen shots is a good one. How about we

1. get a picture for vim with a SoS script (script)
2. get a jupyter notebook with sos script (interactive with picture)
3. get a DAG plus a rq-dashboard with a running sos (workflow)

We tilt and de-focus the pictures to have an effect like the above, we can use the images for the sections below (but we have planned images there), or we can have 

```
SoS (name)
banner text

image1  image2 image3
```

with image1 2, 3 link to relevant sections. Then we only need some simple background (e.g. paper like).

**Comment by BoPeng** [comment]
Something like
![vim](https://cloud.githubusercontent.com/assets/9889312/21171455/db612ada-c191-11e6-8a3f-68442d6e1111.jpg)

Of course a more concise example would be better.

**Comment by BoPeng** [comment]
Could you make the banner background randomly chosen from a directory or files with certain name? It is easy to do as far as I know and we are then free to add representing pictures of sos being used in real life.

**Comment by BoPeng** [comment]
I can see four random pictures, but `sos_screen` never showed up. Is there any reason for this?

**Comment by BoPeng** [comment]
The keyboard one actually looks good, and the google one certainly needs dark text. I suspect `sos_screen` would not look good either. Unless we can set the font color of text (e.g. select color according to filename `mybackground_dark.jpg`), we should avoid using light-background picture.

**Comment by jma7** [comment]
I didn't show sos_screen because of the light background.

**Comment by BoPeng** [comment]
I see. I just used `glob` so that we do not have to change `js` for the addition and removal of images.

**Comment by BoPeng** [comment]
and obviously my copied code does not work. :-)

**Comment by BoPeng** [comment]
Change reverted, keeping only two figures. For the record, `sos_script.js` should be adjusted after adding or removing background figures.

**Comment by jma7** [comment]
I will remove the hard coded image name soon.

**Comment by BoPeng** [comment]
Dark images do look better. We can generate screen shots of vim and jupyter with dark backgrounds later. It would be good to remove hard-coded image names.

I am also not quite sure if it is a good idea to let the background take the whole screen. It is a style though.
