### ISSUE TITLE
Pages on homepage

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#323]
I just added a directory `docs/src/homepage` with some draft design for the introduction and documentation page. We already have an installation page so I did not do it.

Jun: Please feel free to convert the page to md or html if your js code works better with those formats. You can also put all files such as README.md in this folder so that we all know where to make changes. Also, feel free to change the bullet points to tables if tables look better.

Gao: I realize that I am missing a jupyter tutorial with real data analysis and fancy pictures in matploblib and R. I had to use `documentation/SoS_Kernel.html` in the tutorial section but you can add a real tutorial there.

PS: I know it is annoying to have different texts in link text, filename, and title in ipynb, please feel free to rename any of them.

**Comment by gaow** [comment]
Yes I'll put together real data analysis for the tutorials.

**Comment by BoPeng** [comment]
I have revised the three pages overview, documentation, and installation (running sos). I would propose that we use the ipynb converted html file in the homepage so that they have consistent look with other parts of the website, of course without TOC.

Then we only need to worry about the artwork...

**Comment by BoPeng** [comment]
@jma7: it makes sense for the js script (or some other script in `release`) to parse `documentation.html` to get an ordered list of documentation so that we do not have to maintain a separate list of documents.

**Comment by jma7** [comment]
Just want to let you know, I am still working on the home page, not done yet.

**Comment by BoPeng** [comment]
I know. I put a number of small things on the project page as reminders.

**Comment by BoPeng** [comment]
I just added a separate features page to `src/homepage`.

**Comment by BoPeng** [comment]
features should be next to overview (the second tab).
