### ISSUE TITLE
Improvements to doc TOC

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#328]
The new TOC works very well, except that

1. For some reason http://bopeng.github.io/SOS/doc/documentation/SoS_Functions.html does not have toc.
2. The title should be removed from TOC because it overlaps with TOC entry.
3. The TOC could use page `<h1>` as entries, but titles can be long so I am not sure which one should be used. I suppose we can keep using file names as long as the title is removed from TOC. We can always rename files to change their entry in TOC.
4. The "numbering" in TOC is inconsistent (current entry has number and some entries do not). We should either get rid of numbering or make them `6`, `7.1`, etc.
5. We should highlight the  current chapter (for example using blue text color to be consistent with text), or even section when we stroll the page in the TOC. This is especially usable if we remove numbering.
6. We might want to change the "home" text to an icon once we have one for SoS.
7. Can the "Home" button goes to the "Documentation" page of the homepage? It is currently a bit troublesome to switch from tutorial to documentation.

**Comment by BoPeng** [comment]
For 1, I found that the toc exists, but it is the old toc with top buttons, and is located at the end of the page to the left without content. Perhaps the processing script fails for this particular document.

**Comment by jma7** [comment]
The Function_Reference.ipynb file has weird embedding of large chucks  style and javascript in the file which causes the TOC javascript can't work properly. Please generate this ipynb file again.

**Comment by BoPeng** [comment]
OK. I will check tonight.

**Comment by BoPeng** [comment]
This page has a few complete HTML output. I will have to change them.

**Comment by BoPeng** [comment]
Function reference is fixed.

**Comment by gaow** [comment]
> For 1, I found that the toc exists, but it is the old toc with top buttons, and is located at the end of the page to the left without content. Perhaps the processing script fails for this particular document.

What was the actual reason for this, do you recall? I'm trying to publish some of my jupyter notebooks via `sos convert` using the toc template but I'm running into the same issue. Actually the page TOC looks fine offline from my local computer but when it is uploaded online the TOC ends up at the left corner of the page without content ...

**Comment by BoPeng** [comment]
It was because the notebook has some html output (in cell), which has some embedded css files. The css file was generated by RMarkdown and interfered with the TOC.

Anyway, before doing anything, you should clear browser cache. We have run into weird problems that could be resolved by 'Ctrl-reload' (force fresh reload) or clear cache.
