### ISSUE TITLE
Benchmarking of SoS steps

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#5]
I looked at the wiki but I did not see the a [benchmarking](https://bitbucket.org/snakemake/snakemake/wiki/Documentation#markdown-header-benchmark-rules) feature for SoS steps. Perhaps it can be something good to have?

**Comment by bpeng2000** [comment]
Why cannot we do this by default (or with command line option) for every
step as long as users provide a log file? Users can always use a script (or
a tool provided by us) to parse log file and get the details.

Bo

**Comment by bpeng2000** [comment]
We can even save all these to our .runtime directory and provide details or
the statistics through some sort of 'sos analyze' command.

Bo

**Comment by gaow** [comment]
I agree we do this by default and it would be even better to provide an interface to summarize!

**Comment by bpeng2000** [comment]
See proposed interface at
https://github.com/bpeng2000/SOS/blob/master/doc/commandline.md#subcommand-analyze-or-summarize
. Right now we have .sos/.runtime, I guess we can have
.sos/.runtime-datetime etc for individual runs and use the 'sos analyze'
command to gather statistics.

Bo
