### ISSUE TITLE
Progressbar for SoS

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#57]
It seems nice if we can have a progress bar for SoS but not sure how much additional work it is involved -- I seem to remember for VPT we even had matplotlib based summary on workflow progress (or job status?). A text based progress bar would be good enough to me.

**Comment by bpeng2000** [comment]
The problems are

1. We have a lot of output at different levels. A global progress bar can only be displayed at -v0 where it can be displayed without interruption.

2. SoS does not know how much time a step would take to execute so the 'progress' cannot be changed proportional to time spent/left.

3. We currently do not execute workflow in dryrun mode to count the total number of steps so the progress bar would treat nested workflow as part of a step.

A text based progress bar can be easily added if you are fine with these limitations.

**Comment by gaow** [comment]
For verbosity level -v1 is perhaps a good choice. The consequence of 2 and 3 are roughly the same and are understandable. What might disrupt proper display of progress bar might be the stderr and stdout from commandline programs but it is not good idea to print stdxx on screen anyways and we may want to allow for run options to re-direct them to files specified. Other than those, I still find it appealing to have progress bar at -v1 to monitor the runs. Currently there's too much messages displayed at -v2 and too little at -v1.

**Comment by bpeng2000** [comment]
Done. A progress bar is used for each workflow under `-v1`. When nested progress bar is used, the progress bar looks like

```
a:  40.0% [==================>                             ] 2 1.9/s in 00:00:01
sub: 100% [================================================] 4 2.0/s in 00:00:02
a: 100% [==================================================] 5 1.1/s in 00:00:04
```

**Comment by gaow** [comment]
Great! There is a couple of minor issues, though. For example if you run this script [1.sos.txt](https://github.com/bpeng2000/SOS/files/195352/1.sos.txt), twice, via `sos run 1.sos.txt ALL -v1`, you see the output:
```
ALL:   0.0% [>                            ]  in 00:00:00
a: 100% [=================] 2 20.1/s in 00:00:00

a: 100% [===============] 2 22.4/s in 00:00:00
ALL: 100% [==================] 2 9.5/s in 00:00:00
```

There are two issues: 

* Because the nested workflow is `[ALL_1=a_1+b_1]` the workflow name is not `a`. 
* A cosmetic issue:  initial run is good but the rerun (which reuses existing output) will introduce extra line break here.

For issue 1 I propose a patch that checks if the step names in a workflow are the same, and will use `*` for the progressbar name if the steps have different names: 

```diff
@@ -1149,7 +1149,8 @@ class SoS_Workflow:
         #
         # the steps can be executed in the pool (Not implemented)
         # if nested = true, start a new progress bar
-        prog = ProgressBar(self.name, len(self.sections), newLine=nested)
+        bar_title = self.name if len(set([x.name.rsplit('_', 1)[0] for x in self.sections])) == 1 else '*'
+        prog = ProgressBar(bar_title, len(self.sections), newLine=nested)
         for idx, section in enumerate(self.sections):
```

**Comment by bpeng2000** [comment]
progress bar title is fixed. The 'automatic' newline for nested workflow is temporarily removed for a better solution. The new behavior is progress bar from nested workflow will overwrite master progress bar.

**Comment by bpeng2000** [comment]
If we are to display incomplete progress bars properly, there are two solutions

1. A cross-process flag storing the current (even nested) progress bar so that a new progress bar knows if it should start from a new line.

2. A method to know the current cursor location and starts a new line if it is not at the first column. This has the added benefit that a progress bar will always start at the first column (right now it can start from end of text if something has been outputted without newline). However, I do not know a cursor/termio method to tell this.

**Comment by gaow** [comment]
I think the current progress bar is already quite informative, although it would be nice to have the proposed solutions (ideally #2).

**Comment by bpeng2000** [comment]
Encounter the blessings module, which helps us to move cursor around for progress bar. However, in our case the progress bar does not have a fixed location so the following patch does not work. Still something might be interesting for later.

```
diff --git a/pysos/utils.py b/pysos/utils.py
index b52e522..ca7ce66 100644
--- a/pysos/utils.py
+++ b/pysos/utils.py
@@ -34,6 +34,7 @@ import hashlib
 import shutil
 import pickle
 import token
+import blessings
 from tokenize import generate_tokens, untokenize
 from io import StringIO
 from shlex import quote
@@ -399,23 +400,15 @@ logger = env.logger
 #
 # String formatting
 #
-
-
-from array import array
-try:
-    from fcntl import ioctl
-    import termios
-except ImportError:
-    pass
-
 def getTermWidth():
     '''Get the width of current user terminal to properly wrap SoS
     output when well-formatted output is required.
     '''
     try:
-        h, w = array('h', ioctl(sys.stderr, termios.TIOCGWINSZ, '\0' * 8))[:2]
-        return w
-    except:
+        term = blessings.Terminal()
+        return term.width
+    except Exception as e:
+        env.logger.warning(e)
         return 78
 
 class _DeHTMLParser(HTMLParser):
@@ -1139,11 +1132,11 @@ class ProgressBar:
             self.main = ''
             self.finished = 0
             return
+        self.term = blessings.Terminal(stream=sys.stderr)
+        self.location = (10, 4)
         self.main = message
         self.main_start_time = time.time()
         self.message = self.main
-        # get terminal width
-        self.term_width = getTermWidth()
         #
         # total count
         self.count = 0
@@ -1175,14 +1168,16 @@ class ProgressBar:
         if self.totalCount is not None and (count - self.count) < self.min_progress_count:
             return
         self.count = count
-        self.outputProgress()
+        with self.term.location(*self.location):
+            self.outputProgress()
 
     def progress(self, count):
         self.last_progress_count += count
         if self.last_progress_count > self.min_progress_count:
             self.count += self.last_progress_count
-            self.outputProgress()
-            self.last_progress_count = 0
+            with self.term.location(*self.location):
+                self.outputProgress()
+                self.last_progress_count = 0
 
     def outputProgress(self):
         '''Output progress'''
@@ -1233,13 +1228,13 @@ class ProgressBar:
             # percentage
             perc = min(1, float(self.count) / self.totalCount)
             msg[1] = ' {:5.1f}%'.format(perc * 100)
-            width = self.term_width - len(msg[0]) - len(msg[1]) - m3Len - len(msg[4]) - len(msg[5])
+            width = self.term.width - len(msg[0]) - len(msg[1]) - m3Len - len(msg[4]) - len(msg[5])
             if width > 5:
                 front = int(perc * (width - 4))
                 back = width - 4 - front
                 msg[2] = ' [{}>{}]'.format('=' * front, ' ' * back)
         else:
-            width = self.term_width - len(msg[0]) - len(msg[1]) - m3Len - len(msg[4])
+            width = self.term.width - len(msg[0]) - len(msg[1]) - m3Len - len(msg[4])
             msg[6] = ' '*width
         # use stderr to avoid messing up process output
         sys.stderr.write('\r' + ''.join(msg))
@@ -1277,12 +1272,13 @@ class ProgressBar:
         if self.totalCount:
             # percentage
             msg[1] = ' 100%'
-            width = self.term_width - len(msg[0]) - len(msg[1]) - m3Len - len(msg[4]) - len(msg[5])
+            width = self.term.width - len(msg[0]) - len(msg[1]) - m3Len - len(msg[4]) - len(msg[5])
             if width > 4:
                 front = int(width - 3)
                 msg[2] = ' [{}]'.format('=' * front)
-        sys.stderr.write('\r' + ''.join(msg) + '\n')
-        sys.stderr.flush()
+        with self.term.location(*self.location):
+            sys.stderr.write('\r' + ''.join(msg) + '\n')
+            sys.stderr.flush()
 
 
 class frozendict(dict):
diff --git a/setup.py b/setup.py
index e9293fd..ace6047 100644
--- a/setup.py
+++ b/setup.py
@@ -48,6 +48,7 @@ setup(name = "sos",
           'psutil',
           'celery',
           'pyyaml',
+          'blessings',
       ],
     scripts = [
         'sos',

```

**Comment by gaow** [comment]
This feature no longer works well now. It conflicts with what rq shows on the terminal. Also I am not sure how easy it is to make it work well with DAG ... but I am open to the option to creating one single progress bar involving all steps to save the efforts tracking each sub-workflow, and such bar can still be very much informative.

**Comment by BoPeng** [comment]
The progress bar is still there with `-v1`, right?

**Comment by gaow** [comment]
Yes it is still there. However it often gets disrupted by time count down from steps e.g., `worker_1 (00:50:00)` I'm thinking even if this is disabled, because with DAG execution is no longer sequential, it might be hard to have properly working progress bar. But I might be wrong, and in that case we can simply turn off what disrupts it when verbosity is `-v1`

**Comment by BoPeng** [comment]
I see. The progress bar is pretty accurate because it counts down from number of nodes in the DAG. The time count down (actually up) is there because I cannot stand static output, especially if I do not know which step is running. 

I will try to move count down to another line...

**Comment by BoPeng** [comment]
The new behavior lets progress bars manage themselves. Completed progress bars might be overwritten by others but active progress (notification) bars will not overwrite each other....

**Comment by gaow** [comment]
Yes the new behavior is much better now! There is a minor glitch, though. For example here is outcome from a text script in another ticket:
```
[work_1: shared = {'data': 'output'}]
input: "1.txt", "2.txt", group_by = 'single', pattern = '{name}.{ext}'
output: expand_pattern('{_name}.out')
task: concurrent = True
run:
  touch ${_output}

[work_2]
input: "1.txt", "2.txt", group_by = 'single', pattern = '{name}.{ext}', paired_with = ['data']
output: expand_pattern('{_name}.out2')
task: concurrent = True
run:
  touch ${_data} ${_output}

[all]
sos_run("work_1+work_2")
```
and the problem:
```
[GW] sos run test.sos -v1
[GW] 1+work_2: 100% [===============] 2 9.8/s in 00:00:00
```
There should be a line flush at the end of the entire process removing that line of progress bar that remains. Currently the mouse cursor jumps to the front next to the shell command prompt symbol, but the line is not erased.
There should be a Basically the last line

**Comment by gaow** [comment]
I should add that this is not just problem with the progress bar, but also for jobs without progress bar, the flashing `Running XXX (XXX) (00:00:30)` type of prompt does not properly erase itself when it is done, leaving quite a few lines of duplicated text on the console.

**Comment by BoPeng** [comment]
Is it better?

**Comment by gaow** [comment]
Yes the progress bar behavior is fixed. However the time count info from workers is still a bit messed up. See this example:

```
[default_1]
output: 'not_done.txt'
run:
  sleep 6
  touch ${output}

[default_2]
output: 'done.txt'
run:
  sleep 6
  echo ${input} > ${output}
```
and the display after running it
```
[GW] sos run test.sos -v0 -f
[GW] ng default_2 (00:00:05)
```
My cursor jumps to the beginning of 2nd line without erasing the text after.

**Comment by BoPeng** [comment]
Try again.

**Comment by gaow** [comment]
I'm replacing `\n` with `\r\033[K` so that the message is completely removed and with `-v0` one would not get anything on the screen as `-v0` promised. I think the behavior is good now.

**Comment by BoPeng** [comment]
Right now if we have a running progress bar and another progress bar starts, the old one will be moved upward, leaving trace of a partial progress bar. One solution would be using a fixed locations for progress bars (e.g. top of screen), but can also look strange.
