### ISSUE TITLE
default volumes and docker_volumes option

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#75]
Right now docker volumes are determined manually as follows:

```
input_volume = os.path.dirname(fastq_files[0])
output_volume = os.getcwd()

run: docker_image='compbio/ngseasy-fastqc:1.0-r001', 
    docker_volumes=['${input_volume}:/input_data', '${output_volume}:/output_data']
```

we need to 

* determines the directory of the input files (other than input and depends)
* determines where in the docker to mount the input directory (/var/lib/sos? /input_data'?/home/some`?)
* determine the directory of the output files (current working directory?)
* determine where in the docker to mount the output directory ('/output_data'?)

Notes:

* We should try to keep `_input` and `_output` intact within and outside of docker so that the script can be executed within and outside of docker.

* A big limitation of docker volume under mac is that it cannot mount anything outside of `/Users'. I have to manually re-mount my data drive under `/Users` to solve this problem. 

* There can be easier options such as `docker_output_directory`

* We will also need to support sharing docker volumes (e.g. resources). This can be implemented in another option.

**Comment by bpeng2000** [comment]
Right now I am sharing `/Users' to '/Users' under Mac because things outside of `/Users` is not visible to docker and sharing   `/Users' to '/Users'  would make the script more or less compatible inside/outside of docker.
