### ISSUE TITLE
A system that shares many design ideas of SoS (NextFlow)

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#85]
http://www.nextflow.io/blog/2014/using-docker-in-hpc-cluster.html

Based on Java/Groovy

Videos: 

http://www.nextflow.io/presentations.html

**Comment by bpeng2000** [comment]
https://peerj.com/preprints/1171/ contains a comparison of docker performance implemented in nextflow.

**Comment by gaow** [comment]
Yes I too run into this one. I think it will be a very different image if we get ngseasy to work with SoS somewhat seamlessly and be able to say that in the wiki and manuscript.

**Comment by bpeng2000** [comment]
I have found it very easy to use containers from different sources, so we should be able to mix and match containers from these sources for our use. Compare to the current ngsease's bash approach, I think we have clear advantage in flexibility and ease of use, at least there is no need for make install, and sos will automatically download/pull needed containers.

**Comment by BoPeng** [comment]
http://gerritjvv.github.io/glue/workflowdsl.html

Are those all new systems or just we were blind not to see them?

**Comment by gaow** [comment]
Well, I've seen this list quite a while ago:

https://github.com/pditommaso/awesome-pipeline

That was why I thought we should highlight a couple of most distinguished feature of SoS, in addition to claiming that SoS is better engineered than most existing tools (which is a big deal but may not be appreciated without actually using SoS). It does not look like workflowdsl is actively maintained. There was the recent review (that I referenced in the draft manuscript) and I think it is fair enough to not ignore the tools it covered when advocating SoS.

**Comment by BoPeng** [comment]
A pull-request is needed to add SoS there.. :-)

**Comment by BoPeng** [comment]
I had a look at some of the tools I did not know before. My impression is that many people faced the same kind of problems and tried to solve the problems in their own way with the tools they are familiar with, and we are no exception here. Tools backed by a team and some financial support tend to go much further than tools that are created by one or two people, we are unfortunately in the second camp. 

I think SoS can stand out with its simplicity

1. It does not require input/output
2. It does not require the definition of tasks, namely things can be done within SoS
3. It does not require the use of formal python classes (like Luigi and bpipe etc). Although formal python scripts can be very powerful, it requires users to know python and the workflow system very well.
4. Script of scripts, forward and backward styles

However, there are a lot of work to make the simplicity really work in practice, which means, other than bug-free, a lot of small things such as better view/editor (the --html option), early detection and reporting of errors (dryrun mode etc) really matters...
