### ISSUE TITLE
Version control for SoS script

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#86]
Not sure how we can go around this but it can be useful for us to run

```
sos run script:v2
```

if we can manage script in a repository and allow us to retrieve an exact version from command line. I guess this works better for

```
sos run https://github.com/some/path/script.sos:v2 
```

**Comment by gaow** [comment]
Here `v2` has to be a github tag? I think it is good to have this feature, and also support URL in `sos_run`. We previously discussed and disliked the idea to maintain a script repo but at least we can make this possible for others.

**Comment by bpeng2000** [comment]
I meant that I do not want to provide a public repo, at least I do not want to maintain a public repo, but I will have my own private repo. I suppose we can have whatever git or svn supports for versioning, and we can, if not too troublesome, having something like

```
$ sos show URL

normal content

revision 1: date and change log
revision 2: date and change log
```

**Comment by bpeng2000** [comment]
I have allowed the retrieval of the content of URL as a SoS script if a URL is specified, e.g.

```
sos run http://url/to/sos_file
```

but have no idea how to interact with a git repository. In particular, I think it is impossible to download a single file from a repository.

**Comment by gaow** [comment]
But we can parse git URL to the URL pointing to the raw file which seems quite easy... or just provide the raw link, e.g., https://raw.githubusercontent.com/bpeng2000/SOS/master/pysos/sos_script.py

**Comment by bpeng2000** [comment]
This is a github only solution, right?

**Comment by gaow** [comment]
Right. Not sure if we want to treat it a special case -- may worth it if we buy the notion that the future of bioinformatics (statistics, computational biology, you name it) is on github ...

**Comment by bpeng2000** [comment]
But at least we can get the status and history of local files that are tracked by git. For example, if we are given a file that is tracked by git, we can try to get all its previous versions. 

The command to check a file is tracked by git is

```
git ls-files file_name
```
