### ISSUE TITLE
Input not iterable error

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#93]
I have this [1.sos.txt](https://github.com/BoPeng/SOS/files/222446/1.sos.txt) that does not work anymore. When you run it quits on error `'NoneType' object is not iterable`. It looks like it may have something to do with the patch where we indicate "unspecified" input ...

**Comment by MDABioinfo** [comment]
Yes. This is an artifact of allowing unspecified input (None). It should now be fixed but we will need to revisit all these for DAG building.

**Comment by gaow** [comment]
Sorry I clicked close issue when I really wanted to comment: speaking of DAG, how does it work with `dynamic` steps: should we have `dynamic` before implementing DAG, or they are independent tasks?

**Comment by BoPeng** [comment]
Working on it now, but it is not easy.
