### ISSUE TITLE
Making -dpr defalut run mode

### ISSUE THREAD

**Issue by MDABioinfo** [BoPeng/SOS#94]
If `dryrun` and `prepare` mode have the advantage of checking errors earlier, why cannot we make `dpr` default run mode? We can make

`-d`: dry run
`-p`: dry run then prepare mode
`-r`: remove this option because it is default.

**Comment by gaow** [comment]
Absolutely. I add those switches all the time ...

**Comment by BoPeng** [comment]
Done. There is no need for `-dpr` now. The side effect is that the same `input`, `output` stuff will be outputted three times and we will need to reduce them.

**Comment by BoPeng** [comment]
Running script multiple time can have unexpected results. For example, the following script
```
[a_1]
output: '*.html'
import random
for i in range(4):
    with open('something{}.html'.format(random.randint(1, 1000)), 'w') as h:
       h.write(1)
```

will generate 12 instead of 4 files.
