### ISSUE TITLE
No output generated for nested workflow

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#96]
I noticed in one of my application with current SoS that if I execute worflows explictly from command the it runs, but if I execute it within a nested workflow, there is no file generated. See the toy example here
[simulation.txt](https://github.com/BoPeng/SOS/files/228645/simulation.txt). To reproduce:

```
sos run simulation.txt
```
Nothing is generated. But
```
sos run simulation.txt simulate_1
```
then 20 output files `*demo` are generated.  Note that the default workflow contains `simulate_1` as a subflow.

**Comment by BoPeng** [comment]
This is fixed. It is caused by checking input files in preparation mode, which is currently not working without a DAG.

Bo

**Comment by BoPeng** [comment]
In addition, your script uses 

```
output: '${input}.est1.demo'
```

in a few locations, which should be

```
output: '${_input}.est1.demo'
```
