### ISSUE TITLE
Mutable parameters

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#98]
Is it true that there is no global mutable parameters allowed in SoS? I have a task which boils down to something like below:

```
[step_1]
run:
echo ${default.param}

[step_2]
run:
echo ${default.param}

[default: alias = 'default']
param = 2
sos_run('step_1')
param = 3
sos_run('step_2')
```

I understand this is a silly example but this is essentially what I need. Because I understand I cannot make `param` global as I cannot change it in `default`, I tried to see if I can possibly change it inside a step and let other steps call it after the change. Apparently this does not work now. I want to ask what is the correct way to get what I want here in this example. Thank you!

**Comment by BoPeng** [comment]
Nested workflow should see step local variables so your example can be

```
[step_1]
run:
echo ${param}

[step_2]
run:
echo ${param}

[default]
param = 2
sos_run('step_1')
param = 3
sos_run('step_2')
```

**Comment by gaow** [comment]
Great, it works!! :+1:

**Comment by gaow** [comment]
Thank you :)
