### ISSUE TITLE
Problem with pre-specified output name

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#99]
I have an issue with a task that boils down to this:

```
[default]
n = [1000]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
input: for_each = ['n', 'seed']
output: ['{}.rds'.format(x) for x in range(10)]
R: workdir = './', concurrent = True
set.seed(${_seed})
n <- ${_n}
x=rnorm(n)
saveRDS(list(x=x), ${_output!r})
```

When I run it I get an error: 

```
Error: unexpected string constant in "saveRDS(list(x=x), '0.rds' '1.rds'"
```

So it looks like instead of using one element from my pre-specified output  `${output}` at a time it somehow uses two ... Not sure what is wrong but it seems counter intuitive.

**Comment by BoPeng** [comment]
You are specifying all output in `output:` so your `${output}` is the same as `${_output}`. You might be trying to do

```
 output: '${_seed}.rds'
```

**Comment by gaow** [comment]
I see ... my output file names are in fact pre-specified. So I'll perhaps do something like

```
output_files = ['{}.rds'.format(x) for x in range(10)]
output: ${_output_files}
```
and see if that works

**Comment by gaow** [comment]
No it does not work. Usually output is derived from input, but my issue here is that I know the output files beforehand which cannot be derived from any parameters.

**Comment by BoPeng** [comment]
You will have to use

```
input: paired_with='output_files'
```

to get `_output_files` defined.

**Comment by gaow** [comment]
I'm not sure if I get it ... if I write:

```
[default]
n = [1000]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
output_files = ['{}.rds'.format(x) for x in range(10)]
input: for_each = ['n', 'seed'], paired_with = 'output_files'
output: $_output_files}
R: workdir = './', concurrent = True
set.seed(${_seed})
n <- ${_n}
x=rnorm(n)
saveRDS(list(x=x), ${_output!r})
```
Then the error message is: 
```
ERROR: File contains parsing errors: 1.txt
	[line  6]: ${_output_files}
```

And if I write:

```
[default]
n = [1000]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
output_files = ['{}.rds'.format(x) for x in range(10)]
input: for_each = ['n', 'seed'], paired_with = 'output_files'
output: output_files
R: workdir = './', concurrent = True
set.seed(${_seed})
n <- ${_n}
x=rnorm(n)
saveRDS(list(x=x), ${_output_files!r})
```

The the error message becomes
```
ERROR: Failed to process step input : for_each = ['n', 'seed'], paired_with = 'output_files' (Length of variable output_files (length 10) should match the number of input files (length 0).)
```

**Comment by BoPeng** [comment]
I see that you do not have any input file, so I guess your outputfile need to be paired with seed

```
[default]
n = [1000]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
output_files = ['{}.rds'.format(x) for x in range(10)]
input: for_each = ['n', 'seed,output_files']
output: _output_files
```

You should also be able to do

```
[default]
n = [1000]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
output_files = ['{}.rds'.format(x) for x in range(10)]
input: for_each = ['n', 'seed']
output: output_files[_index]
```

**Comment by gaow** [comment]
Great! In fact my output files does not pair with seed. But the `_index` method seems to works! There is still errors in my script which I believe is my fault; still i'll make sure it works before I close the issue. The use of `_index` is not obvious, though ... I'll add some comment to documentation if there is no proposal to create a better interface.
